import { promises as fs } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { env } from "./env";

const MAX_BYTES = 400 * 1024; // ~400KB per frame is plenty for a 640px JPEG.

function sessionDir(sessionId: string): string {
  // sessionId is a cuid generated by us, but resolve+verify anyway so a
  // crafted id can never escape the snapshot root.
  const root = path.resolve(env.snapshotDir);
  const dir = path.resolve(root, sessionId);
  if (!dir.startsWith(root + path.sep) && dir !== root) {
    throw new Error("Invalid session id for snapshot path");
  }
  return dir;
}

/** Persists a data-URL JPEG frame. Returns the stored filename and byte size. */
export async function saveSnapshot(
  sessionId: string,
  dataUrl: string,
): Promise<{ filename: string; bytes: number }> {
  const match = /^data:image\/jpeg;base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl.trim());
  if (!match) throw Object.assign(new Error("Snapshot must be a base64 JPEG data URL"), { status: 400 });

  const buffer = Buffer.from(match[1], "base64");
  if (buffer.byteLength === 0) {
    throw Object.assign(new Error("Empty snapshot"), { status: 400 });
  }
  if (buffer.byteLength > MAX_BYTES) {
    throw Object.assign(new Error("Snapshot too large"), { status: 413 });
  }
  // Reject anything that is not actually a JPEG (magic bytes FF D8 FF).
  if (buffer[0] !== 0xff || buffer[1] !== 0xd8 || buffer[2] !== 0xff) {
    throw Object.assign(new Error("Snapshot is not a JPEG"), { status: 400 });
  }

  const dir = sessionDir(sessionId);
  await fs.mkdir(dir, { recursive: true });
  const filename = `${Date.now()}-${crypto.randomBytes(6).toString("hex")}.jpg`;
  await fs.writeFile(path.join(dir, filename), buffer);
  return { filename, bytes: buffer.byteLength };
}

/** Reads a stored snapshot. Callers must authorise first. */
export async function readSnapshot(sessionId: string, filename: string): Promise<Buffer> {
  if (!/^[0-9]+-[0-9a-f]{12}\.jpg$/.test(filename)) {
    throw Object.assign(new Error("Invalid snapshot name"), { status: 400 });
  }
  return fs.readFile(path.join(sessionDir(sessionId), filename));
}

/** Removes every snapshot for a session — used by the retention endpoint. */
export async function purgeSnapshots(sessionId: string): Promise<void> {
  await fs.rm(sessionDir(sessionId), { recursive: true, force: true });
}

export const snapshotLimit = () => env.snapshotMaxPerSession;
