import type { BankDomain } from "../question-bank";
import { mcq } from "./authoring";

/** Multiple-choice depth — mobile and design fields. See mcq-depth-engineering.ts. */

export const APP_DEV_MCQ: BankDomain = {
  slug: "app-development",
  name: "App Development (Mobile)",
  blurb: "Builds mobile applications for phones and tablets.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "Why should an app avoid blocking the main thread?",
      ["It uses more battery", "The main thread draws the interface, so blocking it freezes the screen and stops touches registering", "It prevents network calls", "The OS forbids it"], 1,
      "Anything over about 16ms drops a frame. A second of blocking looks to the user like the app has crashed."),
    mcq("BEGINNER", "What is the safest place to keep a login token on a device?",
      ["A plain preferences file", "The platform keystore or keychain", "A file in the app's cache folder", "A hard-coded constant"], 1,
      "Keystore-backed storage is hardware-protected and excluded from ordinary backups."),
    mcq("BEGINNER", "A screen loads data every time it appears, even when returning from the next screen. What is the usual fix?",
      ["Load in the app's entry point", "Cache the result and only refetch when it is stale or the user asks", "Disable the back gesture", "Load on a background thread"], 1,
      "Refetching on every appearance wastes the user's data and makes navigation feel slow."),
    mcq("BEGINNER", "Why test on a physical device rather than only a simulator?",
      ["Simulators cannot run the app", "Real devices have slower CPUs, real network conditions, real touch input and real memory pressure", "Simulators do not support debugging", "App stores require it"], 1,
      "A simulator runs on desktop hardware with a desktop network. It hides exactly the problems users hit."),
    mcq("BEGINNER", "What does an app's cache directory guarantee?",
      ["The data persists forever", "Nothing — the OS may clear it at any time when storage is low", "It is encrypted", "It syncs across devices"], 1,
      "Anything the app cannot regenerate must not live there."),
    mcq("BEGINNER", "Why should error messages avoid technical detail?",
      ["To save space", "The user cannot act on a stack trace; they need to know what happened and what to do", "It slows rendering", "Stores reject them"], 1,
      "Log the detail, show the user a plain sentence and a way forward."),
    mcq("BEGINNER", "What happens to a running network request when the user backgrounds the app?",
      ["It always completes", "The OS may suspend the process, so it may never complete or deliver its result", "It is cancelled immediately", "It moves to a system queue"], 1,
      "Work that must finish needs an explicit background task or a server-side design that tolerates the drop."),
    mcq("BEGINNER", "Why is a fixed-height row a problem?",
      ["It renders slowly", "Users with larger system font sizes have their text clipped", "It cannot be scrolled", "It breaks dark mode"], 1,
      "Dynamic type is a common accessibility setting, not an edge case."),
    mcq("BEGINNER", "What is the purpose of an app's splash screen?",
      ["Advertising", "To cover the gap while the app initialises, so the user does not see a blank window", "To load data", "To request permissions"], 1,
      "It should be brief. Using it to preload everything just makes the app feel slow to start."),

    // JUNIOR
    mcq("JUNIOR", "Your list flickers when data refreshes. What is the most likely cause?",
      ["Slow network", "Items are being identified by position rather than a stable id, so the list rebuilds instead of updating", "Images are too large", "The list is not virtualised"], 1,
      "A stable identity lets the framework diff the change rather than replacing everything."),
    mcq("JUNIOR", "What does a deep link need before it acts on its parameters?",
      ["A network check", "Validation and an authorisation check — it is an entry point anyone can invoke", "A splash screen", "Analytics"], 1,
      "Another app can launch it with arbitrary values, including for a user who is not signed in."),
    mcq("JUNIOR", "Why is polling a server every few seconds a poor design on mobile?",
      ["It is unreliable", "It keeps the radio awake, draining battery and data even when nothing changed", "Servers reject it", "It cannot run in background"], 1,
      "Push notification or a long-lived connection delivers the same freshness at a fraction of the cost."),
    mcq("JUNIOR", "What should happen when a user denies a permission the feature needs?",
      ["Ask again immediately", "Explain what the feature does, offer a route to settings, and keep the rest of the app usable", "Close the app", "Disable the account"], 1,
      "Repeated prompting is how a temporary denial becomes a permanent one."),
    mcq("JUNIOR", "Why should image loading be cancelled when a list row is recycled?",
      ["To save memory only", "Otherwise a late response paints the wrong image into a row that now shows different data", "Images cannot be cancelled", "It speeds up scrolling"], 1,
      "This is the classic recycled-cell bug: the right image in the wrong row."),
    mcq("JUNIOR", "What is the practical difference between a crash and an ANR or watchdog termination?",
      ["None", "A crash is an unhandled error; the other is the OS killing an app that stopped responding", "ANRs are less serious", "Crashes only happen in release builds"], 1,
      "They have different causes and different fixes: one is an exception, the other is blocked main-thread work."),
    mcq("JUNIOR", "Your app must show currency amounts. What should you not do?",
      ["Use the device locale", "Store or compute them as floating point", "Show the currency symbol", "Round for display"], 1,
      "Use integer minor units or a decimal type. Floating point accumulates error that eventually contradicts the server."),
    mcq("JUNIOR", "What does certificate pinning protect against?",
      ["Expired certificates", "A trusted-but-malicious certificate authority or a device-installed proxy intercepting traffic", "Weak passwords", "Replay attacks"], 1,
      "It also breaks your app if you rotate certificates without shipping an update, so it needs a rollout plan."),
    mcq("JUNIOR", "Why should analytics events be queued rather than sent immediately?",
      ["To reduce server load", "The device is often offline or on a poor connection, and events should survive that", "Events are large", "It improves accuracy"], 1,
      "Batching also avoids waking the radio for every individual event."),
    mcq("JUNIOR", "A user rotates the device and loses their place in a long list. What went wrong?",
      ["Rotation is not supported", "Scroll position was not preserved across the configuration change", "The list reloaded from network", "The layout is fixed"], 1,
      "Rotation recreates the screen. Anything the user established — scroll, selection, input — has to be restored."),
    mcq("JUNIOR", "What is the risk of shipping verbose logging in a release build?",
      ["Larger binary", "Sensitive data becomes readable to anyone with device access or log tooling", "Slower startup", "Store rejection"], 1,
      "Device logs are readable by other tooling and are routinely attached to bug reports."),
    mcq("JUNIOR", "Why does an app need to handle an expired session mid-action?",
      ["Sessions never expire", "The user may have been idle for days; failing silently loses whatever they were doing", "It is a store requirement", "Tokens cannot be refreshed"], 1,
      "Refresh transparently where possible, and preserve the in-progress action across a re-authentication."),
    mcq("JUNIOR", "What does an app-level feature flag let you do that a store update cannot?",
      ["Change the UI language", "Turn a broken feature off immediately, without waiting for review and adoption", "Reduce binary size", "Bypass permissions"], 1,
      "Installed apps do not roll back. A server-controlled switch is the only immediate lever."),

    // MID
    mcq("MID", "Your crash-free rate is 99.2%. With 500,000 sessions a day, what does that mean?",
      ["It is effectively perfect", "About 4,000 sessions a day end in a crash", "Fewer than 100 users are affected", "The figure is not meaningful"], 1,
      "Percentages hide scale. Translating to affected sessions is what makes the number actionable."),
    mcq("MID", "What is the main correctness risk in an offline-first app?",
      ["Storage limits", "Conflicting edits between the device and the server with no defined resolution rule", "Slow sync", "Battery use"], 1,
      "Last-write-wins silently discards work. The rule has to be an explicit product decision."),
    mcq("MID", "Why is a background sync scheduled by the OS better than a fixed timer?",
      ["It runs more often", "The OS batches it with other wakeups and defers it under low battery, which costs far less power", "Timers are unreliable", "It needs no permission"], 1,
      "Independent wakeups each pay the cost of powering the radio and waking the CPU."),
    mcq("MID", "What does a staged rollout give you that thorough testing does not?",
      ["Fewer bugs", "Exposure to real devices, networks and data at a scale you can halt before it reaches everyone", "Faster review", "Automatic rollback"], 1,
      "It is the only meaningful control once a build is on devices you cannot recall."),
    mcq("MID", "Which is the strongest reason to keep view logic out of platform lifecycle classes?",
      ["File size", "Those classes need a device or heavy harness to instantiate, so logic inside them cannot be tested cheaply", "The OS forbids it", "It improves rendering"], 1,
      "Extracted logic runs in milliseconds in a unit test; the same logic in an activity needs an emulator."),
    mcq("MID", "What problem does a repository layer solve in a mobile app?",
      ["Faster network calls", "One place decides whether data comes from cache, disk or network, so screens do not each invent a policy", "Type safety", "Dependency injection"], 1,
      "Without it, caching and freshness rules get duplicated inconsistently across every screen."),
    mcq("MID", "Why can a memory leak be worse on mobile than on a server?",
      ["Mobile has no garbage collector", "The OS kills the app when it exceeds its memory budget, losing the user's state without warning", "Leaks are harder to detect", "Memory is not reclaimed"], 1,
      "The user experiences it as the app closing itself, usually mid-task."),
    mcq("MID", "What should an app do when it detects it is running on a rooted or jailbroken device?",
      ["Refuse to run", "Decide deliberately based on what is at risk, since detection is defeatable and blocking legitimate users has a cost", "Report the user", "Disable networking"], 1,
      "For a banking app, blocking may be right. For most apps it is a false sense of security that annoys power users."),
    mcq("MID", "Why does app size affect install conversion in emerging markets?",
      ["Stores rank by size", "Users pay for data and often have limited storage, so a large download is abandoned", "Large apps run slower", "It affects review time"], 1,
      "Install conversion is measurable and responds directly to size reduction."),
    mcq("MID", "What is the main argument against putting business rules in a server-driven UI payload?",
      ["It is slower", "Rules become untestable and undebuggable — you cannot reason about the app from its own source", "Payloads get large", "It requires more endpoints"], 1,
      "Server-driven layout is often worthwhile; server-driven logic usually is not."),
    mcq("MID", "Your app must support a device with 2GB of RAM. What changes most?",
      ["The UI framework", "Image decoding, list virtualisation and how much you hold in memory at once", "The network layer", "The build system"], 1,
      "Full-resolution bitmaps are usually the first thing to exhaust a constrained device."),
    mcq("MID", "Why is a token refresh that fires from several concurrent requests a problem?",
      ["It is slow", "Each request may refresh independently, invalidating the others' tokens and logging the user out", "Refresh tokens cannot be reused", "It doubles network traffic"], 1,
      "One in-flight refresh must be shared, with the other requests waiting on it and then retrying."),
    mcq("MID", "What does accessibility testing with a screen reader reveal that an automated checker cannot?",
      ["Contrast failures", "Whether the announced order and wording actually make sense as a task", "Missing labels", "Small tap targets"], 1,
      "Tools catch missing labels; only a person can tell whether the label means anything useful."),
  ],
};

export const UIUX_MCQ: BankDomain = {
  slug: "uiux-design",
  name: "UI/UX Design",
  blurb: "Designs how a product works and how it feels to use.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "Why is a disabled button with no explanation a poor pattern?",
      ["It looks inactive", "The user cannot tell what would enable it, so they are stuck with no next step", "Disabled buttons are inaccessible", "It slows the form"], 1,
      "Either explain the condition, or let them submit and show what needs fixing."),
    mcq("BEGINNER", "What does 'above the fold' assume that is often untrue?",
      ["That the page loads quickly", "That people will not scroll", "That the screen is wide", "That images load"], 1,
      "People scroll readily. What matters is whether the top of the page gives them a reason to."),
    mcq("BEGINNER", "Why should a destructive action not be the default focused button in a dialog?",
      ["It is harder to click", "A user dismissing the dialog with the keyboard would trigger it accidentally", "It looks aggressive", "Dialogs cannot have defaults"], 1,
      "The safe option should be the one that happens when someone acts without reading."),
    mcq("BEGINNER", "What is the problem with a form that validates only on submit?",
      ["It is slower", "The user discovers every mistake at once, after investing effort, and has to hunt for them", "It cannot show errors", "Submission fails"], 1,
      "Validating on blur catches problems near where they were made, while the context is fresh."),
    mcq("BEGINNER", "Why use a person's own words for labels rather than internal terminology?",
      ["It is shorter", "They recognise what they came to do; internal terms describe how the system is built", "It is easier to translate", "It ranks better"], 1,
      "A user manages notifications, not webhook configuration."),
    mcq("BEGINNER", "What does an empty state need beyond saying there is nothing here?",
      ["An illustration", "A reason it is empty and the action that would fill it", "A search box", "A loading indicator"], 1,
      "The empty state is often a user's first screen, so it is a chance to teach rather than a dead end."),
    mcq("BEGINNER", "Why is placing a link's target in the link text important?",
      ["For SEO", "Screen reader users often navigate by listing links out of context, where 'click here' means nothing", "It looks better", "It is required by HTML"], 1,
      "The link text should describe the destination on its own."),
    mcq("BEGINNER", "What is the risk of relying on hover to reveal an action?",
      ["It is slow", "Touch devices have no hover, so the action is effectively hidden", "It uses more code", "It breaks keyboard focus"], 1,
      "Hover can be an enhancement, never the only route to something necessary."),
    mcq("BEGINNER", "Why should a progress indicator show progress rather than just spin?",
      ["Spinners are slower", "A determinate indicator tells the user how long to wait, which changes whether they abandon", "Spinners are inaccessible", "It is easier to build"], 1,
      "Where progress genuinely cannot be measured, a spinner is honest. Where it can, hiding it wastes information."),

    // JUNIOR
    mcq("JUNIOR", "What does a card sort tell you?",
      ["Which visual design people prefer", "How users naturally group and name concepts, which informs navigation structure", "Whether a flow is usable", "How long a task takes"], 1,
      "It is a structure tool, used before layout rather than to evaluate one."),
    mcq("JUNIOR", "Why is 'users want more features' usually a misreading of feedback?",
      ["Users do not know what they want", "Requests are often symptoms — the underlying job is not being served by what already exists", "Features are expensive", "Feedback is biased"], 1,
      "The useful question is what they were trying to do when they felt the need."),
    mcq("JUNIOR", "What does a first-click test measure?",
      ["Reaction time", "Whether the first action a user takes is on the right path, which strongly predicts task success", "Visual appeal", "Error rate"], 1,
      "Users who start down the wrong path rarely recover without help."),
    mcq("JUNIOR", "Why should error text avoid blaming the user?",
      ["It is impolite", "Blame does not help them recover, and most 'user errors' are design failures", "It affects tone of voice guidelines", "It is longer"], 1,
      "Say what happened and what to do next; the cause is rarely worth mentioning."),
    mcq("JUNIOR", "What is the accessibility purpose of a skip link?",
      ["Faster navigation for everyone", "Keyboard users can bypass repeated navigation instead of tabbing through it on every page", "It improves SEO", "It replaces landmarks"], 1,
      "Without it, reaching the main content can take dozens of keystrokes on every page."),
    mcq("JUNIOR", "Why is a modal a poor container for a long form?",
      ["Modals cannot scroll", "It traps the user away from context, is hard to resize, and loses their work if dismissed", "Modals are inaccessible", "Forms cannot be validated in modals"], 1,
      "A modal suits a short, focused decision. A long form deserves a page it can be returned to."),
    mcq("JUNIOR", "What does an interface's 'information scent' refer to?",
      ["Visual polish", "How well a label or link signals what the user will find if they follow it", "Loading speed", "Colour coding"], 1,
      "Weak scent produces pogo-sticking: users repeatedly entering and backing out of sections."),
    mcq("JUNIOR", "Why should a search return results for a misspelling?",
      ["To improve ranking", "Users blame themselves and abandon rather than retrying, so a zero-result page loses them", "Search engines require it", "It reduces load"], 1,
      "Fuzzy matching plus a visible 'showing results for' is what keeps them in the flow."),
    mcq("JUNIOR", "What does the term 'affordance mismatch' describe?",
      ["A layout error", "Something that looks interactive but is not, or looks static but is clickable", "A colour clash", "An unresponsive element"], 1,
      "Both directions cost the user time: one produces dead clicks, the other hides functionality."),
    mcq("JUNIOR", "Why does asking users to rate satisfaction 1–5 often mislead?",
      ["The scale is too small", "It measures a feeling at one moment rather than whether they achieved anything", "Users always pick the middle", "It cannot be analysed"], 1,
      "Task completion, time and error rate describe behaviour; satisfaction describes mood."),
    mcq("JUNIOR", "What is the main design cost of an infinite scroll?",
      ["Performance", "There is no stable position to return to, and anything below the list becomes unreachable", "It cannot be virtualised", "It breaks search"], 1,
      "It suits browsing feeds and works badly for goal-directed searching."),
    mcq("JUNIOR", "Why should a confirmation dialog name the specific thing being acted on?",
      ["It looks more professional", "The user may have lost track of what was selected, and a generic message cannot catch that mistake", "Dialogs require titles", "It aids translation"], 1,
      "'Delete project Apollo?' catches an error that 'Are you sure?' cannot."),

    // MID
    mcq("MID", "A test shows users complete a task faster in version B but report preferring A. What should you do?",
      ["Ship B, since speed wins", "Investigate the gap — preference often reflects confidence or trust, which affects long-term use", "Ship A, since preference wins", "Re-run the test"], 1,
      "Speed on a single supervised task is not the same as willingness to keep using something."),
    mcq("MID", "What does a service blueprint add over a user journey map?",
      ["Visual polish", "The backstage processes and systems that make each step possible, exposing where a failure originates", "Emotional highs and lows", "Persona detail"], 1,
      "It is what lets you see that a slow step is a warehouse process, not an interface problem."),
    mcq("MID", "Why is a design system's contribution process as important as its components?",
      ["It reduces file size", "Without a route to extend it, teams fork components and the system decays", "It satisfies governance", "It speeds up reviews"], 1,
      "Forking is the signal that the escape hatch is cheaper than the contribution path."),
    mcq("MID", "What does 'progressive disclosure' trade away?",
      ["Nothing", "Discoverability — hidden options are harder to find for users who need them", "Visual consistency", "Performance"], 1,
      "It is the right trade when the hidden options serve a minority, and the wrong one when they serve experts using the product daily."),
    mcq("MID", "Why should accessibility be specified in the design rather than left to engineering?",
      ["Engineers cannot do it", "Focus order, announcements and states are design decisions about sequence and meaning", "It is faster", "Tools require it"], 1,
      "Undesigned, the keyboard path follows whatever the markup happened to produce."),
    mcq("MID", "What is the strongest reason to prototype with real data?",
      ["It looks better", "Real names, lengths and volumes break layouts that placeholder content flatters", "It is faster to build", "Stakeholders prefer it"], 1,
      "Lorem ipsum is uniformly short and tidy, which is exactly what real content is not."),
    mcq("MID", "Why can a metric-driven redesign make a product worse overall?",
      ["Metrics are inaccurate", "Optimising one number can degrade another that was not measured, such as support cost or trust", "Users dislike change", "It takes longer"], 1,
      "This is how dark patterns arise from good intentions: conversion rises, retention falls, and only one was watched."),
    mcq("MID", "What does a usability test with five participants reliably give you?",
      ["A success rate", "A list of real problems, without any measure of how common they are", "Statistical confidence", "Preference data"], 1,
      "Treating five people as a percentage is the most common misuse of qualitative research."),
    mcq("MID", "Why is a consistent empty, loading and error treatment worth systematising?",
      ["It saves design time only", "They are the states users hit when something is already going wrong, and inconsistency compounds the confusion", "They are rarely seen", "Engineers request it"], 1,
      "They are also the states most often left undesigned and improvised under deadline."),
    mcq("MID", "What does 'jobs to be done' framing help you avoid?",
      ["Writing personas", "Designing for demographics rather than for what someone is actually trying to accomplish", "User testing", "Feature requests"], 1,
      "Two very different people can share the same job; two similar people can have different ones."),
    mcq("MID", "Why should a designer care about a form's server-side validation messages?",
      ["They are never seen", "They are what the user reads when client validation is bypassed or the state has changed, and they are usually written by nobody", "They affect performance", "They are translated separately"], 1,
      "Unowned error copy is where a careful design meets a raw database message."),
    mcq("MID", "What is the risk of designing an onboarding tour?",
      ["It slows the app", "It teaches the interface rather than delivering value, and is usually skipped or forgotten", "It cannot be skipped", "It requires analytics"], 1,
      "Getting the user to a real outcome quickly teaches more than any tour."),
  ],
};

export const GRAPHIC_MCQ: BankDomain = {
  slug: "graphic-design",
  name: "Graphic Design",
  blurb: "Creates visual work for brand, print and digital.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does a typeface's x-height affect most?",
      ["Print cost", "Apparent size and legibility at small sizes", "Line length", "Colour"], 1,
      "Two faces at the same point size can look very different in size because of it."),
    mcq("BEGINNER", "Why is centred text a poor choice for long body copy?",
      ["It looks informal", "The ragged left edge forces the eye to hunt for the start of each line", "It cannot be justified", "It wastes space"], 1,
      "Centring suits short, symmetrical pieces such as a title or an invitation."),
    mcq("BEGINNER", "What is a spot colour used for?",
      ["Screen display", "A specific pre-mixed ink, used when a colour must match exactly or cannot be reproduced in process printing", "Adding a highlight", "Colour correction"], 1,
      "It is also how metallics and fluorescents are achieved, which CMYK cannot produce."),
    mcq("BEGINNER", "Why keep line length within roughly 45–75 characters?",
      ["It fits standard paper", "Longer lines make it hard for the eye to find the next line, shorter ones break reading rhythm", "It reduces ink use", "It is a legal requirement"], 1,
      "This is why a full-width paragraph on a wide screen is uncomfortable to read."),
    mcq("BEGINNER", "What does adding white space around an element do?",
      ["Wastes the page", "Increases its perceived importance and makes the grouping clearer", "Reduces contrast", "Slows reading"], 1,
      "Proximity signals relationship. Space is how you say two things are not related."),
    mcq("BEGINNER", "Why supply a logo with defined clear space?",
      ["It looks better", "It stops other elements crowding it, which is how identities degrade in other people's hands", "It aids printing", "It is required by trademark law"], 1,
      "Guidelines exist for the people who will use the logo without you in the room."),
    mcq("BEGINNER", "What is the practical problem with a very light grey on white?",
      ["It costs more to print", "It can fall below readable contrast, especially in sunlight or on cheap screens", "It cannot be printed", "It looks dated"], 1,
      "Aim for a measured ratio rather than judging by eye on a calibrated monitor."),
    mcq("BEGINNER", "Why should a design be checked at its final size rather than zoomed in?",
      ["Zoom distorts colour", "Detail that reads at 400% can disappear at actual size, and relationships change", "It is faster", "Software requires it"], 1,
      "Print it, or hold the screen at arm's length. Most fine-detail mistakes are invisible zoomed in."),
    mcq("BEGINNER", "What does a mood board actually achieve on a project?",
      ["Fills time", "It aligns the client and designer on direction before expensive work begins", "Replaces the brief", "Sets the colour palette"], 1,
      "It is a cheap way to discover a disagreement about direction early."),

    // JUNIOR
    mcq("JUNIOR", "A logo will be embroidered on workwear. What constrains the design?",
      ["Colour mode", "Fine detail, thin strokes and small gaps cannot be stitched and will fill in", "File format", "Aspect ratio"], 1,
      "This is why identities need a simplified variant, decided by the designer rather than the embroiderer."),
    mcq("JUNIOR", "Why does a hairline rule sometimes disappear in print?",
      ["Ink coverage", "A stroke defined below the press's minimum reproducible width will not hold", "Wrong colour mode", "Incorrect bleed"], 1,
      "Set a real measured minimum rather than 'hairline', which means different things in different tools."),
    mcq("JUNIOR", "What does a style guide's tone-of-voice section serve?",
      ["Legal protection", "Consistency in how the brand sounds, which matters as much as how it looks", "Translation", "SEO"], 1,
      "An identity that looks coherent and reads inconsistently is only half designed."),
    mcq("JUNIOR", "Why is a design that relies on one specific photograph fragile?",
      ["Licensing cost", "The layout stops working when the image is swapped, which it always eventually is", "Photos compress badly", "It cannot be printed"], 1,
      "Design the treatment — a scrim, a crop rule, a placement grid — so any conforming image works."),
    mcq("JUNIOR", "What is the risk of setting a whole layout in a typeface you have only trialled?",
      ["It may not render", "Licensing for the client's actual uses may be unaffordable or unavailable", "It cannot be embedded", "It lacks glyphs"], 1,
      "Establish the required licences — desktop, web, app, broadcast — before committing."),
    mcq("JUNIOR", "Why check a design in greyscale?",
      ["To prepare for print", "It reveals whether the hierarchy survives without colour, and whether contrast is doing real work", "It reduces file size", "It is faster to proof"], 1,
      "It also predicts how it will look to someone with colour vision deficiency."),
    mcq("JUNIOR", "What does 'rich black' mean and why use it?",
      ["Black with a gloss finish", "Black ink supported by other plates, so large areas do not look washed out", "A darker Pantone", "Overprinted black"], 1,
      "It should not be used for small text, where plate misregistration makes it look blurred."),
    mcq("JUNIOR", "Why is a brand palette usually more than one accent colour?",
      ["Variety", "Real applications need supporting neutrals, states and enough range to build hierarchy", "Printers require it", "It aids recognition"], 1,
      "A one-colour palette forces every piece into the same flat structure."),
    mcq("JUNIOR", "What is the purpose of a design's optical alignment adjustment?",
      ["Correcting software bugs", "Elements that are mathematically aligned can look misaligned, particularly round shapes and punctuation", "Improving print registration", "Meeting grid rules"], 1,
      "The eye is the arbiter. Quotation marks and circles almost always need manual nudging."),
    mcq("JUNIOR", "Why should a designer ask what a piece is competing against?",
      ["To copy it", "Because a design that works in isolation can disappear on a shelf or in a feed", "For pricing", "For legal clearance"], 1,
      "Context determines how much contrast and distinctiveness the piece actually needs."),
    mcq("JUNIOR", "What does supplying a client with outlined type prevent?",
      ["Colour shift", "Missing-font substitution when the file is opened elsewhere", "File corruption", "Scaling problems"], 1,
      "It also makes the text uneditable, so it belongs in final print files rather than working files."),
    mcq("JUNIOR", "Why is 'make it pop' worth interrogating rather than acting on?",
      ["It is rude", "It describes a feeling, not a change — the underlying issue could be hierarchy, contrast or the wrong message", "It is unachievable", "It implies more colour"], 1,
      "Ask what they expect the viewer to notice first. That question usually surfaces the real problem."),

    // MID
    mcq("MID", "What is the main risk of a highly distinctive identity in a conservative sector?",
      ["Printing cost", "It can read as unserious to the audience it needs to persuade, however good it is as design", "It is harder to trademark", "It dates quickly"], 1,
      "Distinctiveness has to be calibrated to what the audience will trust, not to what wins awards."),
    mcq("MID", "Why does a large organisation need brand governance as well as guidelines?",
      ["To restrict designers", "Guidelines answer questions nobody asks; governance is who decides when a case is not covered", "For legal reasons", "To control budgets"], 1,
      "Every real identity meets a case the document did not anticipate."),
    mcq("MID", "What does designing a variable-width logo lockup solve?",
      ["File size", "The mark can hold its proportions and legibility across very different aspect ratios instead of being squeezed", "Colour matching", "Trademark scope"], 1,
      "A single lockup forced into a banner or an app icon is how identities get distorted in practice."),
    mcq("MID", "Why is measuring brand recognition harder than measuring campaign response?",
      ["It is subjective", "It builds slowly and is influenced by everything the company does, so attribution is weak", "It cannot be surveyed", "It changes daily"], 1,
      "That is not a reason to skip measuring it, but it is a reason to be honest about what the number proves."),
    mcq("MID", "What is the strongest argument for designing the smallest application first?",
      ["It is quicker", "If the mark survives a favicon or an app icon, it will survive everything larger", "Small work is cheaper", "Clients see it first"], 1,
      "Designing large first produces detail that has to be thrown away."),
    mcq("MID", "Why should a rebrand plan include internal audiences?",
      ["They approve budgets", "Employees apply the brand daily, and their understanding determines whether it survives contact with reality", "For legal sign-off", "To reduce cost"], 1,
      "An identity nobody internally understands is reinvented by every person who has to use it."),
    mcq("MID", "What does a modular grid enable that a column grid does not?",
      ["Faster layout", "Vertical as well as horizontal structure, which is what makes complex data layouts feel ordered", "Better typography", "Responsive behaviour"], 1,
      "It suits catalogues, dashboards and tabular content where a column grid alone leaves vertical relationships arbitrary."),
    mcq("MID", "Why is a photography direction as much a part of an identity as the logo?",
      ["It is more expensive", "Images occupy far more surface area than the mark and carry most of the impression", "It is easier to control", "Stock is unreliable"], 1,
      "An identity with a strong mark and no image direction looks inconsistent everywhere it is applied."),
    mcq("MID", "What does designing for accessibility change about a brand palette?",
      ["It limits colour choice entirely", "It usually requires defining accessible pairings and often a digital-specific variant", "It forces greyscale", "Nothing"], 1,
      "A brand colour that fails contrast is not unusable — it just cannot carry text."),
    mcq("MID", "Why is a critique that starts with 'I like' or 'I don't like' unhelpful?",
      ["It is impolite", "It gives no criterion, so the designer cannot act on it or judge whether it is right", "It is too brief", "It is subjective"], 1,
      "Useful critique names the objective and asks whether the work meets it."),
    mcq("MID", "What is the practical consequence of a client owning their source files?",
      ["Lower fees", "They can continue the work without you, which is usually right, and should be priced and scoped deliberately", "Copyright transfers automatically", "Files must be simplified"], 1,
      "Whether files transfer is a commercial decision, and it belongs in the agreement rather than in an argument later."),
    mcq("MID", "Why should a designer specify how a layout behaves when content is longer than expected?",
      ["To help engineers", "Real content always overflows eventually, and undesigned overflow gets improvised badly", "It reduces revisions", "It is a print requirement"], 1,
      "Specify truncation, wrapping or scaling explicitly rather than leaving it to whoever builds it."),
  ],
};

export const MCQ_DEPTH_DESIGN: BankDomain[] = [APP_DEV_MCQ, UIUX_MCQ, GRAPHIC_MCQ];
