import type { BankDomain } from "../question-bank";
import { mcq } from "./authoring";

/** Multiple-choice depth — Python, data, infrastructure and QA. See mcq-depth-engineering.ts. */

export const BACKEND_PYTHON_MCQ: BankDomain = {
  slug: "backend-python",
  name: "Backend — Python",
  blurb: "Builds services and data-handling code in Python.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does `enumerate(items)` give you?",
      ["A sorted copy", "Pairs of index and item, so you do not need to track a counter yourself", "The item count", "A reversed list"], 1,
      "It removes the manual index arithmetic where off-by-one errors live."),
    mcq("BEGINNER", "Why is `except Exception` better than a bare `except:`?",
      ["It is faster", "A bare except also catches KeyboardInterrupt and SystemExit, so the program cannot be stopped", "It logs automatically", "It re-raises"], 1,
      "Neither is a good default, but a bare except can make a process genuinely unkillable."),
    mcq("BEGINNER", "What does a set give you over a list?",
      ["Ordering", "Uniqueness, and membership tests that do not scan every element", "Less memory", "Type safety"], 1,
      "`x in some_list` is linear; `x in some_set` is effectively constant."),
    mcq("BEGINNER", "Why should you not modify a list while iterating over it?",
      ["It is slower", "The iterator's positions shift, so elements get skipped silently", "Python forbids it", "It raises an error always"], 1,
      "Build a new list, or iterate over a copy. The failure is silent, which is what makes it dangerous."),
    mcq("BEGINNER", "What is the purpose of `if __name__ == '__main__':`?",
      ["Faster startup", "Code inside runs only when the file is executed directly, not when it is imported", "It defines the entry point for Python", "It enables debugging"], 1,
      "Without it, importing a module runs its script body as a side effect."),
    mcq("BEGINNER", "What does `dict.items()` return?",
      ["A list of keys", "A view of key-value pairs, which reflects later changes to the dictionary", "A sorted dictionary", "A copy of the dictionary"], 1,
      "It is a view, not a snapshot — which matters if the dictionary changes while you hold it."),
    mcq("BEGINNER", "Why is string concatenation in a loop discouraged for large inputs?",
      ["Strings cannot be concatenated", "Strings are immutable, so each step builds a new one, giving quadratic behaviour", "It uses too many variables", "It breaks encoding"], 1,
      "Collect into a list and `\"\".join(...)` once."),
    mcq("BEGINNER", "What does a `requirements.txt` without pinned versions risk?",
      ["Slower installs", "A dependency releasing a breaking change makes a previously working build fail", "Larger images", "License problems"], 1,
      "Pin for applications; ranges are appropriate for libraries."),
    mcq("BEGINNER", "What is the difference between `append` and `extend` on a list?",
      ["None", "`append` adds one item; `extend` adds each element of an iterable", "`extend` sorts", "`append` returns a new list"], 1,
      "`append([1,2])` produces a nested list, which is a common source of confusion."),

    // JUNIOR
    mcq("JUNIOR", "Why does `datetime.now()` without a timezone cause bugs?",
      ["It is slow", "It produces a naive datetime whose meaning depends on the machine's local clock", "It cannot be formatted", "It is deprecated"], 1,
      "Use timezone-aware UTC. Naive datetimes compare and serialise inconsistently across environments."),
    mcq("JUNIOR", "What does a dataclass give you that a plain class does not?",
      ["Validation", "Generated init, repr and equality from the declared fields", "Immutability", "Serialisation"], 1,
      "It generates boilerplate. It does not check types at runtime — the annotations are documentation."),
    mcq("JUNIOR", "Why is `list.pop(0)` a poor way to consume a queue?",
      ["It returns the wrong item", "Removing from the front shifts every remaining element, making it linear per operation", "It raises on empty", "It is not thread safe"], 1,
      "`collections.deque` gives constant-time removal from both ends."),
    mcq("JUNIOR", "What does `__slots__` change about a class?",
      ["It makes it immutable", "It removes the per-instance dictionary, reducing memory and preventing new attributes", "It speeds up methods", "It enables inheritance"], 1,
      "Worth it for millions of small objects; unnecessary complexity otherwise."),
    mcq("JUNIOR", "Why can a module-level mutable default be dangerous in a web service?",
      ["It uses memory", "It is shared across every request handled by that process, so state leaks between users", "It cannot be imported", "It breaks reloading"], 1,
      "Module state persists for the life of the worker, which is exactly how one user sees another's data."),
    mcq("JUNIOR", "What does `yield from` do?",
      ["Returns early", "Delegates iteration to another iterable, forwarding its values and exceptions", "Creates a coroutine", "Flattens nested lists"], 1,
      "It also forwards `send` and `throw`, which matters for generator-based coordination."),
    mcq("JUNIOR", "Why should database sessions not be shared across threads?",
      ["Sessions are slow", "They hold connection and transaction state that is not designed for concurrent use", "Threads cannot use the database", "It causes deadlock always"], 1,
      "A session per request, or per task, is the usual pattern."),
    mcq("JUNIOR", "What is the risk of `pickle.loads` on data from an untrusted source?",
      ["Slow deserialisation", "It can execute arbitrary code during unpickling", "It loses type information", "It cannot handle large objects"], 1,
      "Pickle is a code execution format. Use JSON or another data-only format at any trust boundary."),
    mcq("JUNIOR", "Why does catching an exception and calling `pass` make debugging hard?",
      ["It is slow", "The failure leaves no trace at all, so the symptom appears far from the cause", "It hides the stack", "It swallows return values"], 1,
      "If a failure is genuinely expected and safe, say so in a comment and log at debug level."),
    mcq("JUNIOR", "What does `functools.wraps` preserve on a decorated function?",
      ["Its performance", "Its name, docstring and signature metadata, which tooling and introspection rely on", "Its arguments", "Its return type"], 1,
      "Without it, every decorated function reports itself as the wrapper."),
    mcq("JUNIOR", "Why is `is` the wrong operator for comparing strings?",
      ["It is slower", "It compares identity, and equal strings are not guaranteed to be the same object", "It is deprecated", "It only works on numbers"], 1,
      "Small strings are often interned, which makes the bug appear to work in testing."),
    mcq("JUNIOR", "What does an ORM's `bulk_create` avoid?",
      ["Validation", "One round trip per row, which dominates the cost for large inserts", "Transactions", "Index updates"], 1,
      "It also usually skips signals and per-instance logic, which is the trade-off."),

    // MID
    mcq("MID", "Why is a thread pool the wrong tool for CPU-bound Python work?",
      ["Threads are unavailable", "The GIL prevents genuine parallel execution of Python bytecode, so they take turns", "Thread creation is slow", "Threads cannot return values"], 1,
      "Processes bypass it, at the cost of memory and inter-process communication."),
    mcq("MID", "What problem does dependency injection solve in a Python service?",
      ["Import speed", "Collaborators can be substituted in tests without patching module globals", "Circular imports", "Type checking"], 1,
      "Heavy `mock.patch` use is usually a sign that dependencies are being reached for rather than passed in."),
    mcq("MID", "Why can `select_related` make a query slower rather than faster?",
      ["It adds a subquery", "Joining wide tables can multiply the data transferred well beyond what separate queries would cost", "It disables the index", "It fetches all rows"], 1,
      "`prefetch_related` issues a second query instead, which is often cheaper for one-to-many."),
    mcq("MID", "What does an async context manager give you over a regular one?",
      ["Better performance", "Setup and teardown that can await, such as acquiring and releasing a connection", "Automatic retries", "Thread safety"], 1,
      "Using a synchronous context manager for I/O inside a coroutine blocks the loop."),
    mcq("MID", "Why is mutating a shared dictionary from several asyncio tasks usually safe, but from threads not?",
      ["Dictionaries are thread safe", "Coroutines only yield at await points, so a block without an await is not interrupted", "asyncio adds locking", "Threads copy the dictionary"], 1,
      "It is a fragile guarantee: adding an await inside the block silently reintroduces the race."),
    mcq("MID", "What does `contextvars` provide that a thread-local does not?",
      ["Faster access", "Correct per-task isolation in asyncio, where many tasks share one thread", "Persistence across requests", "Type safety"], 1,
      "Thread-locals leak between concurrent tasks on the same thread, which is how request context gets crossed."),
    mcq("MID", "Why should a long-running Celery task checkpoint its progress?",
      ["To report to the user only", "A worker can be killed mid-task, and without a checkpoint the whole thing restarts", "Tasks time out", "It reduces memory"], 1,
      "Combined with idempotency, checkpointing turns a restart into a resume."),
    mcq("MID", "What is the risk of using `Decimal` and `float` in the same calculation?",
      ["It raises TypeError always", "The float's existing imprecision is carried into the Decimal result, defeating the point of using it", "It is slower", "Decimals lose precision"], 1,
      "Keep money in Decimal or integers end to end; the moment a float touches it, exactness is gone."),
    mcq("MID", "Why does an unbounded `lru_cache` on a request-scoped function leak?",
      ["It never expires", "Every distinct argument set is retained for the life of the process", "It is not thread safe", "It caches exceptions"], 1,
      "Set `maxsize`, and be careful what is in the key — arguments are held as long as the entry is."),
    mcq("MID", "What does a WSGI server's worker model mean for in-memory caches?",
      ["They are shared", "Each worker process holds its own, so hit rates fall and values can disagree", "They are disabled", "They persist across restarts"], 1,
      "Sizing a per-worker cache also multiplies its memory by the worker count."),
    mcq("MID", "Why should a service avoid importing heavy modules at module scope?",
      ["It breaks linting", "Import cost is paid at startup for every worker, even on code paths that never use it", "Imports fail", "It causes circular imports"], 1,
      "Deferring the import into the function that needs it keeps boot fast."),
    mcq("MID", "What does structured logging give you over formatted strings?",
      ["Smaller output", "Fields that can be filtered and aggregated, rather than text that has to be parsed with regular expressions", "Faster writes", "Automatic redaction"], 1,
      "It is the difference between querying a field and grepping a sentence."),
  ],
};

export const DATA_ENG_MCQ: BankDomain = {
  slug: "data-engineering",
  name: "Data Engineering",
  blurb: "Builds the pipelines and models that turn raw data into something trustworthy.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does a UNION do that a JOIN does not?",
      ["Filters rows", "Stacks rows from two result sets on top of each other rather than widening rows side by side", "Removes duplicates only", "Aggregates"], 1,
      "UNION also removes duplicates; UNION ALL keeps them and is usually faster."),
    mcq("BEGINNER", "Why is a column named `status` with free-text values a problem?",
      ["It uses more storage", "Typos and variants proliferate, so filters silently miss rows", "It cannot be indexed", "It breaks joins"], 1,
      "A constrained set of values, enforced by the database, is what keeps a filter honest."),
    mcq("BEGINNER", "What does `COALESCE(a, b)` return?",
      ["The larger value", "`a` if it is not null, otherwise `b`", "Both concatenated", "Null if either is null"], 1,
      "It is how you supply a default without a CASE expression."),
    mcq("BEGINNER", "Why does a report suddenly showing zero rows often mean an upstream change rather than a bug?",
      ["Reports do not break", "A renamed column, a changed status value or a shifted schema silently stops matching", "Zero is impossible", "The database was restarted"], 1,
      "The query is doing exactly what it was told; what it was told no longer describes the data."),
    mcq("BEGINNER", "What is a surrogate key?",
      ["A composite of business columns", "A system-generated identifier with no business meaning, used to identify a row", "A foreign key", "An index"], 1,
      "It stays stable when the business identifier changes, which natural keys tend to do."),
    mcq("BEGINNER", "Why should a pipeline record when it ran and what it processed?",
      ["For billing", "Without it you cannot tell whether missing data means a failure or genuinely nothing arrived", "It is required by SQL", "To speed up reruns"], 1,
      "Run metadata is what turns 'the number looks wrong' into an answerable question."),
    mcq("BEGINNER", "What does aggregating with AVG over a column containing nulls do?",
      ["Treats nulls as zero", "Ignores them, so the average is over the non-null rows only", "Returns null", "Raises an error"], 1,
      "That is usually right, but it means the denominator is not the row count — which surprises people."),
    mcq("BEGINNER", "Why keep a raw copy of source data?",
      ["Storage is cheap", "Transformation logic changes and contains mistakes, and without the raw data you cannot reprocess", "It is required for audits", "It speeds up queries"], 1,
      "Discarding the input makes every past transformation bug permanent."),
    mcq("BEGINNER", "What is the difference between a view and a table?",
      ["Views are faster", "A view is a stored query evaluated on read; a table holds materialised rows", "Views cannot be queried", "Tables cannot be joined"], 1,
      "A materialised view is the middle ground: stored results that must be refreshed."),

    // JUNIOR
    mcq("JUNIOR", "Why does `WHERE date_column::date = '2026-01-01'` often ignore an index?",
      ["Dates cannot be indexed", "Applying a function to the column prevents the index on it from being used", "The comparison is a string", "It needs a composite index"], 1,
      "Compare against a range instead, so the raw column is used directly."),
    mcq("JUNIOR", "What does a composite index on (a, b) help with?",
      ["Only queries filtering on b", "Queries filtering on a, or on a and b together — not on b alone", "Any combination", "Only exact matches"], 1,
      "Column order matters. A query on b alone usually cannot use it."),
    mcq("JUNIOR", "Why is a nightly full reload sometimes better than an incremental one?",
      ["It is faster", "It is far simpler and self-correcting, which matters more than efficiency until the data is large", "Incremental loads are unreliable", "It uses less storage"], 1,
      "Incremental loads accumulate subtle drift. A full reload is the cheapest correctness guarantee at modest scale."),
    mcq("JUNIOR", "What does a data pipeline's watermark represent?",
      ["A quality score", "The point up to which data is considered complete, so processing knows what is safe to compute", "A row count", "An index"], 1,
      "Setting it too aggressively produces silently understated results for late-arriving data."),
    mcq("JUNIOR", "Why is `COUNT(DISTINCT user_id)` expensive on a very large table?",
      ["It scans twice", "Distinct counting requires tracking every value seen, which does not reduce with parallelism as easily as a sum", "It cannot use indexes", "It locks the table"], 1,
      "Approximate algorithms such as HyperLogLog trade a small error for a large saving."),
    mcq("JUNIOR", "What does partitioning by ingest date rather than event date affect?",
      ["Nothing", "Queries filtering by event date cannot prune partitions, so they scan everything", "Storage cost only", "Write throughput"], 1,
      "Partition on the column your queries actually filter by."),
    mcq("JUNIOR", "Why should a transformation be deterministic?",
      ["To run faster", "So the same input always yields the same output, making reruns and comparisons meaningful", "To use less memory", "It is required by SQL"], 1,
      "Non-determinism — an unordered tie-break, a call to now() — makes a rerun produce a different answer with no explanation."),
    mcq("JUNIOR", "What is a slowly changing dimension type 1?",
      ["Keeps full history", "Overwrites the old value in place, keeping no history", "Adds a new row per change", "Stores changes in a separate table"], 1,
      "It is appropriate for correcting errors and wrong for anything a historical fact should be attributed against."),
    mcq("JUNIOR", "Why does a LEFT JOIN followed by a WHERE on the right table behave like an INNER JOIN?",
      ["It does not", "The WHERE filters out the null rows the outer join produced", "The optimiser rewrites it", "Left joins are inner joins"], 1,
      "Put the condition in the ON clause if you want to keep the unmatched rows."),
    mcq("JUNIOR", "What does schema-on-read give up compared with schema-on-write?",
      ["Flexibility", "Guarantees — malformed data is accepted at write time and only discovered by whoever reads it", "Query speed", "Storage efficiency"], 1,
      "It moves the cost from the producer to every consumer, which is usually a worse trade at scale."),
    mcq("JUNIOR", "Why is deduplicating by `SELECT DISTINCT *` risky?",
      ["It is slow", "It hides the cause and will collapse legitimately distinct rows once a column is added", "It cannot be indexed", "It changes column order"], 1,
      "Deduplicate on the declared grain with an explicit tie-break, not on the whole row."),

    // MID
    mcq("MID", "What does a lakehouse table format such as Iceberg or Delta add over plain files?",
      ["Compression", "Atomic commits, schema evolution and time travel over object storage", "Faster scans only", "A query engine"], 1,
      "It brings transactional guarantees to a storage layer that has none."),
    mcq("MID", "Why is `MERGE` on a very large table often slower than expected?",
      ["It is single threaded", "It must match every source row against the target, so without pruning it becomes a full comparison", "It rebuilds indexes", "It locks the database"], 1,
      "Restricting the target by partition or key range is what makes it tractable."),
    mcq("MID", "What is the practical difference between a fact table's additive and semi-additive measures?",
      ["None", "Additive measures can be summed across every dimension; semi-additive ones cannot be summed across time", "Semi-additive measures are approximate", "Additive measures cannot be averaged"], 1,
      "An account balance is the classic semi-additive measure: summing it across days is meaningless."),
    mcq("MID", "Why should a pipeline fail loudly rather than write partial output?",
      ["Partial output is slower", "Downstream consumers cannot distinguish partial data from a genuine business change", "It corrupts the table", "It wastes storage"], 1,
      "Writing atomically — to a staging location then swapping — means consumers never see a half-written state."),
    mcq("MID", "What does column-level lineage let you do that table-level lineage does not?",
      ["Run faster queries", "Tell exactly which downstream fields a specific source column feeds, so a change's impact is precise", "Detect duplicates", "Enforce access control"], 1,
      "Table-level lineage over-reports impact, which trains people to ignore it."),
    mcq("MID", "Why is a nightly job that depends on another team's nightly job fragile?",
      ["It is slower", "The dependency is implicit and time-based, so a delay upstream silently produces stale or empty output", "Jobs cannot depend on each other", "It doubles cost"], 1,
      "Depend on data availability — a sensor or a signal — rather than on a clock."),
    mcq("MID", "What is the main risk of pushing business logic into the BI tool?",
      ["Slow dashboards", "Definitions diverge per dashboard and cannot be tested, versioned or reused", "It costs more", "It cannot join tables"], 1,
      "This is how two dashboards end up with two different revenue numbers, both defensible."),
    mcq("MID", "Why does a columnar format speed up analytical queries?",
      ["Compression only", "A query reads only the columns it needs, and similar values compress well together", "It stores fewer rows", "It indexes automatically"], 1,
      "It is correspondingly poor for retrieving whole individual rows, which is what transactional systems do."),
    mcq("MID", "What does an assertion test on a pipeline output typically check?",
      ["Query syntax", "Properties that must hold — uniqueness on the grain, no unexpected nulls, volume within a range", "Execution time", "Storage cost"], 1,
      "They catch the silent failures that a successful run status does not."),
    mcq("MID", "Why is reprocessing history harder in a streaming pipeline than a batch one?",
      ["Streams cannot be replayed", "State and windowing are built up over time, so replaying requires reconstructing that state correctly", "Streams are slower", "Storage is limited"], 1,
      "This is why many teams keep a batch path alongside the stream specifically for backfills."),
    mcq("MID", "What does a semantic layer centralise?",
      ["Storage", "Metric definitions, so every tool computing revenue computes it the same way", "Access control", "Query caching"], 1,
      "A definition expressed as code and executed is the only kind that stays true."),
  ],
};

export const DEVOPS_MCQ: BankDomain = {
  slug: "devops-cloud",
  name: "DevOps / Cloud Infrastructure",
  blurb: "Builds and operates the infrastructure and delivery pipeline products run on.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does a container image not include?",
      ["Application code", "The host kernel — containers share it rather than bundling one", "Dependencies", "Configuration defaults"], 1,
      "That is why containers start in milliseconds and why a Linux container cannot run on a Windows kernel unaided."),
    mcq("BEGINNER", "Why should configuration come from the environment rather than the image?",
      ["Smaller images", "The same tested artefact can then run in staging and production without rebuilding", "It is faster", "Images cannot hold files"], 1,
      "Rebuilding per environment means the thing you tested is not the thing you shipped."),
    mcq("BEGINNER", "What does `docker exec` into a running production container risk?",
      ["Nothing", "Changes made are invisible to the image and vanish on restart, creating a state nobody can reproduce", "It stops the container", "It exposes a port"], 1,
      "Debugging that way is fine; fixing that way is how servers become unrepeatable."),
    mcq("BEGINNER", "Why does a firewall rule allowing 0.0.0.0/0 on a database port matter?",
      ["It is slower", "The database is reachable from the entire internet, protected only by its password", "It breaks replication", "It disables TLS"], 1,
      "Database ports are scanned constantly. Network-level restriction is the first control, not the password."),
    mcq("BEGINNER", "What is the purpose of tagging cloud resources?",
      ["Faster provisioning", "Attributing cost and ownership, so spend can be explained and orphans found", "Improving security", "Enabling backups"], 1,
      "An untagged estate cannot answer 'who owns this and can we delete it'."),
    mcq("BEGINNER", "Why run a container as a non-root user?",
      ["It starts faster", "A container escape or a compromised process then has fewer privileges on the host", "It is required by registries", "It reduces image size"], 1,
      "Defence in depth. It does not make an escape impossible, it makes it less useful."),
    mcq("BEGINNER", "What does a rolling deployment do?",
      ["Deploys to all instances at once", "Replaces instances gradually, so some capacity is always serving", "Runs both versions permanently", "Deploys to a copy of production"], 1,
      "It requires the two versions to coexist safely, which constrains database changes."),
    mcq("BEGINNER", "Why should backups be restored periodically rather than just taken?",
      ["To free storage", "An untested backup is an assumption; restores fail for reasons only a real attempt reveals", "It refreshes the data", "It is a compliance rule"], 1,
      "The failure modes are usually missing credentials, missing dependencies, or a restore time nobody measured."),
    mcq("BEGINNER", "What does infrastructure drift mean?",
      ["Slow provisioning", "The live environment no longer matches its definition, usually from a manual change", "Resources moving region", "Cost increasing"], 1,
      "Applying the definition then silently reverts whatever emergency fix someone made by hand."),

    // JUNIOR
    mcq("JUNIOR", "Why is a readiness probe that checks a downstream service dangerous?",
      ["It is slow", "A brief dependency blip removes every instance from the load balancer at once", "Probes cannot make network calls", "It causes restarts"], 1,
      "Report on your own ability to serve. Degrade gracefully rather than declaring yourself unready."),
    mcq("JUNIOR", "What does a pod disruption budget protect against?",
      ["Node failure", "Voluntary disruptions such as a node drain taking down more replicas than you can afford", "Out-of-memory kills", "Image pull failures"], 1,
      "It constrains planned operations. It cannot help with an unplanned node loss."),
    mcq("JUNIOR", "Why should a CI job not have permanent production credentials?",
      ["Jobs run slowly", "Anyone who can open a pull request can potentially run code with those credentials", "Credentials expire", "It is a compliance rule"], 1,
      "Short-lived, scoped credentials issued per run bound the damage of a malicious or mistaken change."),
    mcq("JUNIOR", "What does horizontal pod autoscaling need in order to work sensibly?",
      ["A large cluster", "A metric that actually correlates with the bottleneck, and resource requests set realistically", "A fixed replica count", "A service mesh"], 1,
      "Scaling on CPU when the constraint is database connections makes the incident worse."),
    mcq("JUNIOR", "Why is `latest` risky even in a development environment?",
      ["It downloads slowly", "Two machines can run different code while believing they are identical", "It is not cached", "Registries reject it"], 1,
      "The confusion it causes during debugging costs far more than the convenience it saves."),
    mcq("JUNIOR", "What does a sidecar container pattern typically provide?",
      ["Redundancy", "A supporting capability such as log shipping or a proxy, sharing the pod's lifecycle and network", "A backup of the main container", "Faster startup"], 1,
      "It keeps cross-cutting concerns out of the application image."),
    mcq("JUNIOR", "Why does storing Terraform state locally break a team?",
      ["It is insecure only", "Two people applying concurrently have no shared view and can destroy each other's resources", "It is slower", "It cannot be versioned"], 1,
      "Remote state with locking is what makes concurrent work safe."),
    mcq("JUNIOR", "What is the practical purpose of a canary analysis step?",
      ["Slower rollout", "Comparing the new version's error rate and latency against the old one before proceeding", "Testing in staging", "Reducing cost"], 1,
      "A canary without a comparison is just a slow deploy that still ships the problem."),
    mcq("JUNIOR", "Why should log retention be finite?",
      ["Logs are inaccurate", "Cost grows without bound, and old logs are usually a liability rather than an asset", "Logs corrupt over time", "Compliance forbids retention"], 1,
      "Retention should be a deliberate decision per log type, not a default of forever."),
    mcq("JUNIOR", "What does an init container let you do?",
      ["Run the app faster", "Perform setup that must complete before the main container starts, such as a migration or a config fetch", "Restart the pod", "Share memory"], 1,
      "It runs to completion first, which is what makes ordering guarantees possible."),
    mcq("JUNIOR", "Why is monitoring disk usage on a log-writing host important?",
      ["Logs slow the disk", "A full disk takes down the application, often in ways that look unrelated", "It affects backups", "It changes permissions"], 1,
      "A full disk is one of the most common causes of an outage with a confusing symptom."),

    // MID
    mcq("MID", "What does a service mesh give you that a library cannot?",
      ["Faster calls", "Consistent traffic policy, mTLS and telemetry across services regardless of language, without changing them", "Type safety", "Cheaper hosting"], 1,
      "The cost is a substantial new operational surface, which is why it needs a polyglot estate to justify."),
    mcq("MID", "Why is a blue-green deployment expensive for a stateful service?",
      ["Twice the compute only", "The data has to be consistent across both environments, and cutting over mid-write is the hard part", "It cannot be automated", "It requires downtime"], 1,
      "It is straightforward for stateless services and a significant design problem once state is involved."),
    mcq("MID", "What does a chaos experiment aim to establish?",
      ["That the system fails", "Whether the system behaves as designed under a failure you chose deliberately, before one you did not", "How fast recovery is", "Which service is weakest"], 1,
      "It is only worth running where you have a hypothesis and a way to stop it."),
    mcq("MID", "Why is an alert without a runbook link a design flaw?",
      ["It is harder to route", "The person paged at 3am has to reconstruct context that someone already knew", "Alerts must have documentation", "It cannot be silenced"], 1,
      "The value of an alert is the action it triggers. Without one, it is just noise with a severity."),
    mcq("MID", "What does immutability buy you at the infrastructure level?",
      ["Lower cost", "Every instance is created the same way, so there is no accumulated manual state to explain a difference", "Faster boot", "Better security patching"], 1,
      "It converts configuration management from an ongoing problem to a build-time one."),
    mcq("MID", "Why does a multi-AZ database not protect against a bad migration?",
      ["It does", "Replication faithfully copies the damage to every replica", "Replicas are read-only", "Failover reverts changes"], 1,
      "Availability and recoverability are different properties. Backups address one, replication the other."),
    mcq("MID", "What is the main operational cost of running your own Kubernetes control plane?",
      ["Compute", "Upgrades, certificate rotation and etcd operations that a managed offering absorbs", "Networking", "Storage"], 1,
      "It is rarely justified unless you have a requirement no managed offering meets."),
    mcq("MID", "Why should a deployment pipeline be able to deploy the current production version?",
      ["For testing", "Rolling forward to a known-good build is often safer than rolling back, and it proves the pipeline works", "It saves artefacts", "It is a compliance rule"], 1,
      "A pipeline that can only deploy new commits leaves you with no path during an incident."),
    mcq("MID", "What does a request-scoped trace id need in order to be useful across services?",
      ["A shared database", "Propagation in headers, and every service honouring and forwarding it", "A service mesh", "Structured logging"], 1,
      "One service dropping it breaks the chain for everything downstream."),
    mcq("MID", "Why is autoscaling on a queue's depth often better than on CPU?",
      ["It is cheaper", "Queue depth directly represents unserved demand, whereas CPU is a proxy that may not correlate", "CPU is unreliable", "Queues scale faster"], 1,
      "Scale on the thing that represents the backlog, not on a resource that may not be the constraint."),
    mcq("MID", "What does a well-chosen SLO give an engineering team?",
      ["A performance target", "A shared basis for deciding when to prioritise reliability over features", "A monitoring dashboard", "An uptime guarantee"], 1,
      "Without a consequence attached, it is a number nobody acts on."),
  ],
};

export const QA_MCQ: BankDomain = {
  slug: "qa-automation",
  name: "QA / Test Automation",
  blurb: "Finds what is broken before users do, and builds the tests that keep it that way.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What makes a bug report reproducible?",
      ["A screenshot", "Exact steps from a known starting state, with expected and actual results", "A severity rating", "A stack trace"], 1,
      "Without a starting state, steps that work for the reporter often fail for everyone else."),
    mcq("BEGINNER", "Why test with an empty dataset as well as a populated one?",
      ["It is faster", "Empty states are frequently undesigned and untested, and they are what a new user sees first", "It reduces setup", "Databases require it"], 1,
      "The first screen a customer sees is often the one nobody exercised."),
    mcq("BEGINNER", "What is exploratory testing?",
      ["Testing without a plan", "Simultaneous learning, test design and execution, guided by what is found", "Manual regression testing", "Testing new features only"], 1,
      "It is structured — usually time-boxed with a charter — but the next test depends on the last result."),
    mcq("BEGINNER", "Why should a test have exactly one reason to fail?",
      ["It runs faster", "When it fails, the cause is unambiguous without further investigation", "It uses fewer assertions", "Frameworks require it"], 1,
      "A test asserting five unrelated things tells you something broke but not what."),
    mcq("BEGINNER", "What does testing a boundary value mean?",
      ["Testing the largest input", "Testing at and either side of a limit, where off-by-one errors live", "Testing invalid input", "Load testing"], 1,
      "If the rule is 'over 100', test 99, 100 and 101."),
    mcq("BEGINNER", "Why is 'it works on my machine' worth investigating rather than dismissing?",
      ["It is usually a lie", "The difference between the two environments is itself the finding", "Machines are identical", "It is a configuration issue"], 1,
      "That difference is often what a customer will hit too."),
    mcq("BEGINNER", "What should a tester do when a requirement is ambiguous?",
      ["Test the most likely interpretation", "Raise it before testing, because an ambiguous requirement produces an ambiguous product", "Test all interpretations", "Skip that area"], 1,
      "Ambiguity found at test time is cheap; found after release it is a support cost."),
    mcq("BEGINNER", "Why record the environment in a bug report?",
      ["For statistics", "Browser, device, version and account state frequently determine whether the bug reproduces", "It is a template field", "For routing"], 1,
      "Most 'cannot reproduce' resolutions come down to an unrecorded environment difference."),
    mcq("BEGINNER", "What does severity describe, as distinct from priority?",
      ["How soon to fix", "How bad the effect is when it happens; priority is how soon it gets fixed", "How often it happens", "How hard it is to fix"], 1,
      "A severe bug affecting nobody can be low priority; a cosmetic bug on the signup page may not be."),

    // JUNIOR
    mcq("JUNIOR", "Why is asserting on an exact error message brittle?",
      ["Messages are long", "Copy changes for reasons unrelated to behaviour, breaking the test without a real regression", "Messages are translated", "Assertions are slow"], 1,
      "Assert on the error type, code, or that an error is shown at all."),
    mcq("JUNIOR", "What does a test seam allow?",
      ["Faster execution", "Substituting a real dependency with a controllable one at a defined boundary", "Parallel tests", "Coverage measurement"], 1,
      "Without one, testing requires the real database, clock or network."),
    mcq("JUNIOR", "Why should test data be created by the test rather than seeded globally?",
      ["It is faster", "Shared fixtures create hidden coupling, so one test's change breaks another", "Seeds are unreliable", "It reduces database size"], 1,
      "Self-contained tests can also run in parallel, which shared state prevents."),
    mcq("JUNIOR", "What is the problem with a test that sleeps for a fixed duration?",
      ["It is imprecise", "It is simultaneously too short on a slow machine and wasted time on a fast one", "Sleeps are blocked in CI", "It affects other tests"], 1,
      "Wait for the condition with a timeout, not for a duration."),
    mcq("JUNIOR", "Why is testing through the public interface usually preferable?",
      ["It is easier", "Tests survive refactoring, because they assert on behaviour rather than structure", "It is faster", "It gives better coverage"], 1,
      "Tests coupled to internals break every time the internals improve, which discourages improvement."),
    mcq("JUNIOR", "What does a smoke test suite exist to answer?",
      ["Is every feature correct", "Is this build fundamentally working enough to be worth testing further", "Is performance acceptable", "Are there regressions"], 1,
      "It should be fast and cover the critical path only."),
    mcq("JUNIOR", "Why does high coverage on a module with no assertions mean nothing?",
      ["Coverage is inaccurate", "Coverage records that a line executed, not that its behaviour was checked", "Assertions are counted separately", "It measures only branches"], 1,
      "Mutation testing measures whether the tests would notice a change; coverage does not."),
    mcq("JUNIOR", "What is the risk of a test that only runs in CI and not locally?",
      ["It is slower", "Developers cannot reproduce or debug its failures, so it gets ignored or disabled", "CI is unreliable", "It duplicates effort"], 1,
      "A test people cannot run is a test people stop trusting."),
    mcq("JUNIOR", "Why check a feature's behaviour when a permission is missing?",
      ["Permissions rarely fail", "It is a real user state, and undesigned permission failures usually surface as a blank screen or a crash", "It is a security test", "Stores require it"], 1,
      "Denied and revoked permissions are common in practice and rarely in the test plan."),
    mcq("JUNIOR", "What does testing with a screen reader reveal that a checker cannot?",
      ["Colour contrast", "Whether the announced sequence and wording make sense as a task", "Missing alt text", "Focus outlines"], 1,
      "Automated tools find missing labels; only a person can judge whether a present label is meaningful."),
    mcq("JUNIOR", "Why should a regression suite grow deliberately rather than by adding a test per bug?",
      ["Tests are expensive", "An unmanaged suite becomes slow and duplicative, and slow suites stop being run", "Bugs recur rarely", "Coverage plateaus"], 1,
      "A test per bug is a reasonable default; a suite nobody prunes is not."),

    // MID
    mcq("MID", "What does a consumer-driven contract test verify?",
      ["That both services are deployed", "That the provider still satisfies the expectations a specific consumer relies on", "End-to-end behaviour", "Schema validity"], 1,
      "It lets each side deploy independently while still catching interface drift."),
    mcq("MID", "Why is a test environment shared between teams a source of flakiness?",
      ["It is slower", "Concurrent activity changes data and state underneath a running test", "It has less capacity", "Deployments are queued"], 1,
      "Isolated data per test, or ephemeral environments, is what removes the coupling."),
    mcq("MID", "What does property-based testing generate that example-based testing does not?",
      ["More assertions", "Inputs you would not have thought of, checked against an invariant rather than a fixed expectation", "Performance data", "Coverage reports"], 1,
      "It also shrinks a failing case to its minimal form, which makes debugging much faster."),
    mcq("MID", "Why is measuring escaped defects more useful than counting bugs found?",
      ["It is easier", "It measures what the process missed, which is the thing you can actually improve", "Found bugs are not tracked", "It correlates with coverage"], 1,
      "Bugs found is an activity metric; bugs escaped is an outcome metric."),
    mcq("MID", "What does a quarantine for flaky tests achieve?",
      ["It deletes them", "The suite stays trustworthy while the flaky test is tracked and fixed rather than silently ignored", "It reduces runtime", "It improves coverage"], 1,
      "Quarantine without an owner and a deadline is just deletion with extra steps."),
    mcq("MID", "Why is load testing against a scaled-down environment misleading?",
      ["It is too slow", "Bottlenecks do not scale linearly — connection limits, caches and contention behave differently", "It costs the same", "Tools require production"], 1,
      "It can still find gross problems; it cannot tell you the real ceiling."),
    mcq("MID", "What does testing a rollback path protect against?",
      ["Deployment failure", "Discovering during an incident that the rollback itself is broken, usually because of a schema change", "Data loss", "Slow deploys"], 1,
      "A rollback that has never been exercised is a plan, not a capability."),
    mcq("MID", "Why does adding retries to an end-to-end suite hide real bugs?",
      ["Retries are slow", "An intermittent product bug becomes indistinguishable from test flakiness", "Retries change state", "CI counts them as failures"], 1,
      "Track retry rates per test so the signal is preserved even when the retry is pragmatic."),
    mcq("MID", "What is the strongest argument for testing in production?",
      ["It is cheaper", "Some conditions — real data, real scale, real traffic patterns — cannot be reproduced anywhere else", "It replaces staging", "It is faster"], 1,
      "It complements pre-release testing and needs guardrails: flags, canaries and the ability to stop."),
    mcq("MID", "Why should a test suite be ordered randomly?",
      ["To spread load", "It surfaces order dependencies caused by leaked state, instead of hiding them behind a fixed sequence", "It improves coverage", "Frameworks default to it"], 1,
      "A suite that only passes in one order has hidden coupling that will eventually bite."),
  ],
};

export const MCQ_DEPTH_INFRA: BankDomain[] = [
  BACKEND_PYTHON_MCQ,
  DATA_ENG_MCQ,
  DEVOPS_MCQ,
  QA_MCQ,
];
