import type { BankDomain } from "../question-bank";
import { mcq } from "./authoring";

/**
 * Multiple-choice depth — engineering fields.
 *
 * Measured cause of repeats: a paper typically draws 4–6 multiple-choice
 * questions, and the exact-difficulty pool held 10–16. Four drawn from ten is
 * a 40% chance of any given question appearing, which is what a recruiter
 * generating a few links in a row actually notices. Rotation cannot fix a
 * shallow pool — only depth can, so this takes the drawn-from-most type to
 * roughly 24 per level.
 */

export const FULLSTACK_MCQ: BankDomain = {
  slug: "fullstack-development",
  name: "Full Stack Development",
  blurb: "Builds both the interface and the server behind it.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What is the difference between GET and POST?",
      ["GET is faster", "GET asks for data and should not change anything; POST sends data intended to change something", "POST is more secure", "GET cannot send parameters"], 1,
      "GET is meant to be safe and repeatable. A GET that deletes a record will eventually be triggered by a crawler or a prefetch."),
    mcq("BEGINNER", "Your form posts and the page reloads, losing everything. What is most likely missing?",
      ["A database connection", "The submit handler is not preventing the browser's default form submission", "A CSS rule", "An index on the table"], 1,
      "Without preventDefault the browser does a full navigation, which is the classic cause of a form that appears to do nothing."),
    mcq("BEGINNER", "What does a primary key guarantee?",
      ["The column is indexed for speed only", "Each row has a value that is unique and not null, so a row can always be identified", "The column cannot be changed", "Rows are stored in that order"], 1,
      "Uniqueness plus not-null is what makes a row addressable. Most databases index it as a side effect, but that is not the guarantee."),
    mcq("BEGINNER", "Where does JavaScript in a web app actually run?",
      ["Only in the browser", "In the browser, and on the server if the app uses a server-side runtime such as Node", "Only on the server", "In the database"], 1,
      "The same language runs in both places with different capabilities — the browser has the DOM, the server has the filesystem."),
    mcq("BEGINNER", "What is the point of a git branch?",
      ["To back up the repository", "To develop a change in isolation so the main line stays working", "To make the repository smaller", "To share code with other projects"], 1,
      "Isolation is the point. It is what lets an unfinished feature exist without blocking a release from main."),
    mcq("BEGINNER", "A page requests data and shows nothing while it waits. What should it show instead?",
      ["Nothing, to avoid flicker", "An indication that it is loading, so the user knows the click registered", "An error message", "The previous page's data"], 1,
      "Silence reads as broken and people click again. Acknowledging the action is the minimum."),
    mcq("BEGINNER", "What is the difference between a 401 and a 403 response?",
      ["They are interchangeable", "401 means you are not authenticated; 403 means you are authenticated but not allowed", "401 is for pages, 403 is for APIs", "403 means the server is down"], 1,
      "401 invites the client to authenticate. 403 says authentication will not help — the identity is known and refused."),
    mcq("BEGINNER", "Why keep business logic out of the database query layer?",
      ["Queries run slower with logic in them", "Logic spread across SQL and application code becomes impossible to find and test in one place", "Databases cannot express logic", "It uses more connections"], 1,
      "The cost is discoverability. A rule that lives half in a trigger and half in a service is a rule nobody can change confidently."),
    mcq("BEGINNER", "What does deploying to 'staging' before production give you?",
      ["Faster deploys", "A chance to run the exact build against realistic configuration before users see it", "Automatic rollback", "Lower hosting cost"], 1,
      "Its value depends entirely on how closely it matches production. A staging environment that has drifted proves nothing."),

    // JUNIOR
    mcq("JUNIOR", "A user uploads a file and your server stores it using the filename they supplied. What is the risk?",
      ["The file may be too large", "A crafted name such as ../../etc/passwd can write outside the intended directory", "The upload will be slow", "The filename may be unreadable"], 1,
      "Path traversal. Generate your own name and treat the supplied one as display text only."),
    mcq("JUNIOR", "Which of these belongs in a database transaction?",
      ["Sending a confirmation email", "Debiting one account and crediting another", "Writing a log line", "Calling a third-party API"], 1,
      "Both writes must succeed or neither. Email and external calls cannot be rolled back, so they belong outside."),
    mcq("JUNIOR", "What does an HTTP ETag enable?",
      ["Compression of the response", "A conditional request, so an unchanged resource returns 304 with no body", "Encryption of the payload", "Rate limiting"], 1,
      "It saves bandwidth on unchanged resources and can also be used to detect concurrent modification on writes."),
    mcq("JUNIOR", "Your app stores a user's timezone as an offset such as +05:00. What breaks?",
      ["Nothing", "Daylight saving — the offset changes twice a year, so stored times drift", "Sorting by time", "Storing the value"], 1,
      "Store the IANA zone name such as Europe/London. The offset is derived from the zone and the date, not a property of the user."),
    mcq("JUNIOR", "What problem does a foreign key constraint prevent?",
      ["Duplicate rows", "Rows referring to a parent record that does not exist", "Slow joins", "Null values"], 1,
      "It stops orphans. Application-level checks miss the concurrent case where the parent is deleted between check and insert."),
    mcq("JUNIOR", "Why is `SELECT *` a problem in application code?",
      ["It is slower to type", "The result silently changes shape when a column is added or renamed, and it fetches data you do not need", "It cannot be used with joins", "It bypasses indexes"], 1,
      "Explicit columns make the contract visible and let the database serve some queries from an index alone."),
    mcq("JUNIOR", "A REST endpoint returns 200 with an empty array when no records match. Is that right?",
      ["No, it should return 404", "Yes — the collection exists and is legitimately empty", "No, it should return 204", "No, it should return 400"], 1,
      "404 means the collection itself does not exist. An empty result is a successful answer to a valid question."),
    mcq("JUNIOR", "What does hashing a password with a salt prevent?",
      ["Brute force attacks", "Precomputed rainbow tables, and two users with the same password having the same hash", "Network interception", "SQL injection"], 1,
      "Salt defeats precomputation. Slowness — bcrypt's work factor — is what defeats brute force."),
    mcq("JUNIOR", "You need to run a long import triggered by a web request. What is the right shape?",
      ["Run it in the request and raise the timeout", "Accept the request, queue the work, and return a way for the client to check progress", "Run it in a database trigger", "Split it across several requests from the client"], 1,
      "Holding a connection open for minutes ties up a worker and dies with any proxy timeout."),
    mcq("JUNIOR", "What is the practical difference between authentication middleware and authorisation checks?",
      ["They are the same", "Authentication establishes who is calling; authorisation decides whether that identity may do this specific thing", "Authentication runs after authorisation", "Authorisation only applies to admins"], 1,
      "Authentication is global; authorisation is per-resource and cannot be handled once in middleware."),
    mcq("JUNIOR", "Your API is called from a mobile app you cannot update quickly. What does that change?",
      ["Nothing", "Responses must stay backward compatible, because old clients will exist for months", "You must version every endpoint", "You cannot use JSON"], 1,
      "Old app versions persist on devices. Adding optional fields is safe; removing or renaming is not."),
    mcq("JUNIOR", "What does a database migration's 'down' step exist for?",
      ["Deleting old data", "Reversing the change if the deploy has to be rolled back", "Compressing the table", "Rebuilding indexes"], 1,
      "It is only useful if it has been tested. An untested down migration is a comforting fiction during an incident."),
    mcq("JUNIOR", "Two requests both check 'does this username exist' and both insert. What prevents a duplicate?",
      ["Checking twice", "A unique constraint at the database level", "A longer transaction", "Retrying the request"], 1,
      "Check-then-insert is a race. Only the database can enforce it atomically."),

    // MID
    mcq("MID", "Which is the strongest reason to put a read model behind a materialised view?",
      ["It reduces storage", "An expensive read-time aggregation becomes a cheap lookup, at the cost of staleness", "It removes the need for indexes", "It enforces referential integrity"], 1,
      "You are trading freshness for latency. That trade is only correct if the consumer can tolerate the lag."),
    mcq("MID", "Your service returns 200 but takes 30 seconds under load. Which metric would have warned you first?",
      ["Total request count", "Latency at a high percentile, measured against an objective", "CPU utilisation", "Error rate"], 1,
      "Error rate stays flat because nothing failed. The p99 is where a slow path shows up long before it becomes a timeout."),
    mcq("MID", "What does optimistic concurrency control use to detect a conflict?",
      ["A row lock held for the duration", "A version or timestamp compared at write time, rejecting the write if it changed", "A serialisable transaction", "A distributed lock"], 1,
      "Nothing is locked; the conflict is detected at commit. It suits low-contention data where blocking would cost more than the occasional retry."),
    mcq("MID", "Why is storing a JWT's expiry as the only revocation mechanism risky?",
      ["Tokens cannot expire", "Until it expires, a stolen or revoked token remains valid and nothing can stop it", "Expiry is not signed", "Clients ignore expiry"], 1,
      "Statelessness is the feature and the problem. Short access tokens with a server-checked refresh token is the usual balance."),
    mcq("MID", "You must add full-text search over a million rows. What is the first thing to establish?",
      ["Which search library is fastest", "What users actually search for, and whether the database's own search is sufficient", "How much RAM is available", "Whether to use Elasticsearch or Solr"], 1,
      "Introducing a second datastore adds sync, consistency and operational cost. Postgres full-text search covers a great many cases."),
    mcq("MID", "What does a correlation id in your logs give you?",
      ["Faster log writes", "The ability to reconstruct one user's request across every service it touched", "Smaller log volume", "Automatic alerting"], 1,
      "Without it, logs from concurrent requests interleave and cannot be untangled after the fact."),
    mcq("MID", "Your background worker and web process share a database. What is the main failure mode under load?",
      ["Schema drift", "The worker's long transactions hold connections and locks that starve the web process", "Duplicate deploys", "Cache invalidation"], 1,
      "Separate connection pools, and short transactions in the worker, are what keep one from taking down the other."),
    mcq("MID", "When is denormalising a schema defensible?",
      ["Whenever it makes queries shorter", "When a measured read path is too slow and the duplication has a clear owner keeping it consistent", "When the ORM is awkward", "Never"], 1,
      "The cost is that the same fact now lives in two places. That is only worth paying against evidence, with a defined write path."),
    mcq("MID", "What is the risk of catching an exception, logging it, and returning a default value?",
      ["Logging is slow", "The caller cannot tell a real result from a failure, so corruption spreads silently", "Defaults use more memory", "The stack trace is lost"], 1,
      "A swallowed error becomes a wrong answer that looks correct. Either handle it meaningfully or let it propagate."),
    mcq("MID", "Why does adding a second application server sometimes make an app slower?",
      ["Load balancers add latency", "Shared bottlenecks such as the database or a lock now receive twice the pressure", "The code has to be recompiled", "Sessions cannot be shared"], 1,
      "Scaling the layer that was not the constraint just applies more load to the one that was."),
    mcq("MID", "What does 'least privilege' mean for a service's database user?",
      ["A short password rotation", "It has only the rights it needs — often no DDL, and no access to tables it never reads", "It connects over TLS", "It uses a connection pool"], 1,
      "It bounds the damage of an injection or a compromised process. A service running as the schema owner can drop everything."),
    mcq("MID", "You need to expose an operation that is expensive and rarely used. What is a sensible design?",
      ["Make it a synchronous endpoint and document the wait", "Make it asynchronous with a job id, and rate limit it per caller", "Run it on a schedule instead", "Cache the result indefinitely"], 1,
      "Expensive plus rare is exactly the shape that takes a service down when someone loops over it."),
    mcq("MID", "What problem does content-hashing static asset filenames solve?",
      ["Smaller files", "Assets can be cached forever, because a change produces a new filename", "Faster compression", "Better SEO"], 1,
      "It removes the cache-invalidation problem entirely: the URL is the version."),
  ],
};

export const FRONTEND_MCQ: BankDomain = {
  slug: "frontend-react",
  name: "Frontend — React / TypeScript",
  blurb: "Builds the interface users touch, in React and TypeScript.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does `className` do in JSX rather than `class`?",
      ["Nothing, both work identically", "`class` is a reserved word in JavaScript, so JSX uses `className` for the same attribute", "`className` applies styles inline", "`className` is for components only"], 1,
      "It compiles to the same HTML class attribute. The rename exists purely because JSX is JavaScript."),
    mcq("BEGINNER", "Why should a list item's key be stable across renders?",
      ["To improve CSS performance", "React uses it to decide which item is which, so an unstable key discards and rebuilds the element", "Keys are shown in devtools", "It prevents duplicate items"], 1,
      "An unstable key loses focus, scroll position and input state on every render."),
    mcq("BEGINNER", "What is the difference between `display: none` and `visibility: hidden`?",
      ["They are the same", "`display: none` removes the element from layout; `visibility: hidden` leaves the space it occupied", "`visibility: hidden` deletes the element", "`display: none` only works on block elements"], 1,
      "Both hide from screen readers. If you want it hidden visually but still announced, neither is correct."),
    mcq("BEGINNER", "A button does nothing when clicked and there is no console error. What is the most likely cause?",
      ["The browser is out of date", "The handler was passed as `onClick={handler()}` — calling it during render instead of passing the function", "CSS is blocking the click", "React is not installed"], 1,
      "Calling it during render passes the return value, usually undefined, as the handler."),
    mcq("BEGINNER", "What does `useState` give you that a plain variable does not?",
      ["Faster reads", "A value that survives re-renders, and a setter that tells React to re-render when it changes", "Type safety", "Access from other components"], 1,
      "A plain variable is reinitialised every render and changing it never triggers an update."),
    mcq("BEGINNER", "Why is inline `style={{...}}` a poor default for most styling?",
      ["It is slower to parse", "It cannot express hover, focus, media queries or pseudo-elements", "It is not supported in production builds", "It overrides accessibility settings"], 1,
      "It also creates a new object every render. Fine for one dynamic value, wrong as a general approach."),
    mcq("BEGINNER", "What does semantic HTML give you that a page of divs does not?",
      ["Smaller file size", "Structure that assistive technology, search engines and keyboard navigation can all use", "Faster rendering", "Automatic styling"], 1,
      "A `<button>` is focusable, activates on space and enter, and announces itself. A div needs all of that rebuilt by hand."),
    mcq("BEGINNER", "Where should shared state between two sibling components live?",
      ["Duplicated in both", "In their closest common parent, passed down as props", "In a global variable", "In localStorage"], 1,
      "Lifting to the nearest common ancestor keeps one source of truth without reaching for global state."),
    mcq("BEGINNER", "What is a controlled input?",
      ["An input with validation", "One whose displayed value comes from state, so React is the source of truth", "A disabled input", "An input inside a form element"], 1,
      "The alternative leaves the value in the DOM, which is fine until you need to read or reset it programmatically."),

    // JUNIOR
    mcq("JUNIOR", "What does the dependency array of `useEffect` actually control?",
      ["How often the component renders", "When the effect re-runs after a render, by comparing the values by reference", "Whether the effect is async", "The order effects run in"], 1,
      "Comparison is by identity, which is why inline objects and functions cause effects to run every time."),
    mcq("JUNIOR", "Why is `key={Math.random()}` always wrong?",
      ["Random numbers are slow", "A new key every render means React unmounts and remounts the element every time", "Keys must be strings", "It breaks TypeScript"], 1,
      "It guarantees the worst case: full teardown, lost state, and no reconciliation benefit at all."),
    mcq("JUNIOR", "What does `aria-label` do that visible text does not?",
      ["Changes the visual label", "Provides an accessible name when there is no visible text, such as an icon-only button", "Improves search ranking", "Adds a tooltip"], 1,
      "If there is visible text, prefer it — an aria-label that disagrees with the visible label confuses voice control users."),
    mcq("JUNIOR", "Your component re-renders when an unrelated part of a context changes. Why?",
      ["Context is global", "Any consumer re-renders when the context value changes, regardless of which part it uses", "Context does not memoise", "The provider is misconfigured"], 1,
      "Splitting into several contexts, or selecting with a subscription, is the usual remedy."),
    mcq("JUNIOR", "What does TypeScript's `unknown` give you over `any`?",
      ["Better performance", "You must narrow it before use, so the compiler still protects you", "It accepts fewer values", "It is only for errors"], 1,
      "`any` disables checking; `unknown` defers it. `unknown` is the correct type for parsed JSON."),
    mcq("JUNIOR", "A form submits before validation finishes. What is likely wrong?",
      ["Validation is too slow", "The submit handler is not awaiting the async validation before proceeding", "The form has no action attribute", "The inputs are uncontrolled"], 1,
      "An async validator that is not awaited resolves after the submit has already gone."),
    mcq("JUNIOR", "What is the accessibility problem with a click handler on a `<div>`?",
      ["Divs cannot have handlers", "It is not focusable, not announced as interactive, and does not respond to enter or space", "The handler fires twice", "It breaks CSS"], 1,
      "Adding tabIndex, role and key handlers reproduces a button badly. Use a button."),
    mcq("JUNIOR", "Why does fetching in `useEffect` without cleanup cause problems?",
      ["It leaks memory always", "A response arriving after unmount, or after a newer request, can overwrite current state", "Effects cannot be async", "Fetch is not supported"], 1,
      "An AbortController, or a flag checked before setting state, prevents the stale write."),
    mcq("JUNIOR", "What does `React.memo` actually skip?",
      ["State updates", "A re-render caused by the parent, when the props compare equal", "Effects", "The initial render"], 1,
      "It compares props shallowly. A new inline object or callback prop defeats it entirely."),
    mcq("JUNIOR", "Which is the strongest argument for CSS custom properties over a preprocessor variable?",
      ["Shorter syntax", "They exist at runtime, so they can be changed by theme, media query or JavaScript", "Better browser support", "They compile faster"], 1,
      "A preprocessor variable is gone after build. A custom property is live and cascades."),
    mcq("JUNIOR", "Your bundle includes a date library used in one component. What reduces the cost most simply?",
      ["Minify more aggressively", "Load that component's code lazily so the library is not in the initial bundle", "Switch to a smaller library", "Move it to a CDN"], 1,
      "A smaller library also helps, but code splitting removes it from the critical path entirely."),
    mcq("JUNIOR", "What does `prefers-reduced-motion` exist for?",
      ["Saving battery", "Users for whom animation causes nausea or migraine can ask for it to be reduced", "Slower devices", "Print styles"], 1,
      "It is an accessibility setting, not a performance one. Respecting it usually means replacing motion with a fade or nothing."),
    mcq("JUNIOR", "Why can two components rendering the same hook not share its state?",
      ["Hooks are global", "Each call creates its own independent state; a hook shares logic, not values", "Hooks cannot hold state", "The second call fails"], 1,
      "Sharing values requires lifting the state or using a context — the hook itself is just reusable behaviour."),

    // MID
    mcq("MID", "What does React's concurrent rendering allow that blocking rendering does not?",
      ["Multi-threaded rendering", "An in-progress render can be interrupted so urgent updates such as typing stay responsive", "Parallel network requests", "Server rendering"], 1,
      "It is still single-threaded. The gain is interruptibility, not parallelism."),
    mcq("MID", "You need to animate a list reorder smoothly. What is the main constraint?",
      ["CSS transitions cannot animate reorder", "Layout-affecting properties trigger reflow, so transform-based techniques are what stay at 60fps", "React blocks animation", "Keys prevent animation"], 1,
      "Animating top/left forces layout every frame. Transform and opacity are composited."),
    mcq("MID", "What is the practical risk of storing derived data in state?",
      ["It uses more memory", "It can drift out of sync with its source, producing a UI that contradicts itself", "State cannot hold objects", "It prevents memoisation"], 1,
      "Derive during render where you can. State should hold what cannot be computed."),
    mcq("MID", "Why is a virtualised list harder to make accessible?",
      ["It cannot use semantic elements", "Only a window of items exists in the DOM, so screen readers cannot perceive the full set or its size", "Keys are unstable", "It disables focus"], 1,
      "Declaring the total count and position with ARIA is what restores the missing context."),
    mcq("MID", "What does a Content Security Policy protect against?",
      ["CSRF", "Injected scripts executing, by restricting which sources the browser will run", "SQL injection", "Session fixation"], 1,
      "It is a containment layer for XSS, not a replacement for escaping output."),
    mcq("MID", "Your app's state library causes the whole tree to re-render on any change. What is the usual fix?",
      ["Use fewer components", "Subscribe to slices of state rather than the whole store", "Memoise every component", "Move state into context"], 1,
      "Selector-based subscription means only components reading the changed slice re-render."),
    mcq("MID", "What problem does an optimistic update introduce?",
      ["Slower perceived response", "The UI has asserted something the server may reject, so a rollback path must exist", "Extra network requests", "Loss of type safety"], 1,
      "Rolling back silently is worse than waiting. The failure has to be visible and recoverable."),
    mcq("MID", "Which is the most reliable way to detect a memory leak in a single-page app?",
      ["Watch the task manager", "Take heap snapshots across repeated navigation and compare retained objects", "Count components", "Measure bundle size"], 1,
      "Detached DOM nodes and listeners retained by closures are what the comparison exposes."),
    mcq("MID", "Why is `dangerouslySetInnerHTML` named that way?",
      ["It is slow", "It bypasses React's escaping, so any untrusted content in it executes as markup and script", "It cannot be undone", "It breaks hydration"], 1,
      "Sanitising server-side, or with a vetted library, is the only safe way to use it."),
    mcq("MID", "What does a design token buy over a hard-coded colour?",
      ["Smaller CSS", "One place to change, and a name that expresses intent so themes can reassign it", "Faster rendering", "Automatic contrast checking"], 1,
      "Semantic naming — surface, danger — survives a rebrand. A token called blue-500 does not."),
    mcq("MID", "Your first contentful paint is fast but the page is unusable for two seconds. What is the likely cause?",
      ["Slow server", "A large JavaScript bundle parsing and executing before the page becomes interactive", "Too many images", "Missing CSS"], 1,
      "Content painted from server HTML appears quickly; interactivity waits for the bundle."),
    mcq("MID", "What is the strongest reason to type API responses rather than trusting them?",
      ["Better autocomplete", "A type annotation is not a runtime check — the server can send anything, and parsing at the boundary catches it", "It reduces bundle size", "It prevents CORS errors"], 1,
      "Validating at the trust boundary with a schema library is what makes the type honest."),
    mcq("MID", "Why does server-side rendering not automatically improve perceived speed?",
      ["It always does", "If the page still ships a large bundle before it responds to input, the user sees content they cannot use", "SSR is slower to build", "Search engines run JavaScript"], 1,
      "SSR moves the first paint earlier. Time to interactive is a separate problem with a separate fix."),
  ],
};

export const BACKEND_NODE_MCQ: BankDomain = {
  slug: "backend-node",
  name: "Backend — Node.js / APIs",
  blurb: "Builds the services, APIs and data layer behind a product.",
  questions: [
    // BEGINNER
    mcq("BEGINNER", "What does `package-lock.json` do?",
      ["Prevents editing package.json", "Records the exact resolved version of every dependency so installs are reproducible", "Locks the project to one Node version", "Compresses node_modules"], 1,
      "Without it, a caret range can resolve differently on another machine or next week."),
    mcq("BEGINNER", "Why should a server validate the Content-Type of an incoming request?",
      ["To improve speed", "So it does not attempt to parse a body in a format it did not expect", "It is required by HTTP", "To enable compression"], 1,
      "Parsing an unexpected format either throws or, worse, succeeds with something you did not intend."),
    mcq("BEGINNER", "What does a middleware function do in Express?",
      ["Handles the database", "Runs on the way to the handler and can inspect, modify, or end the request", "Renders templates", "Manages the connection pool"], 1,
      "Ordering matters — an auth middleware registered after the route it protects never runs."),
    mcq("BEGINNER", "What happens if a Node process throws an uncaught exception?",
      ["The request fails and the server continues", "The process exits by default, taking every in-flight request with it", "It is logged and ignored", "Node restarts automatically"], 1,
      "This is why handlers catch their own errors and why a process manager restarts the service."),
    mcq("BEGINNER", "Why store a timestamp in UTC?",
      ["It is smaller", "It is unambiguous — local times repeat and skip around daylight saving", "It sorts faster", "It is required by SQL"], 1,
      "Convert to local time at the point of display, using the viewer's zone."),
    mcq("BEGINNER", "What does an API returning 204 mean?",
      ["The request failed", "It succeeded and there is deliberately no body to return", "The resource moved", "Authentication is required"], 1,
      "Common for a successful DELETE. Sending a body with 204 is a protocol violation."),
    mcq("BEGINNER", "Why should log output go to standard out rather than a file the app manages?",
      ["It is faster", "The platform can collect, rotate and ship it, and the app stays stateless", "Files are not durable", "It uses less disk"], 1,
      "An app writing its own log files has to solve rotation and disk exhaustion itself."),
    mcq("BEGINNER", "What is the risk of an endpoint that accepts arbitrary JSON and passes it to a database update?",
      ["Slow parsing", "Mass assignment — a caller can set fields such as role or isAdmin that were never meant to be writable", "Encoding errors", "Larger payloads"], 1,
      "Pick the permitted fields explicitly rather than spreading the request body."),
    mcq("BEGINNER", "What does a health check endpoint exist for?",
      ["Monitoring user activity", "So an orchestrator can tell whether this instance should receive traffic or be replaced", "Measuring latency", "Reporting errors"], 1,
      "It should report on the process itself. Checking every dependency turns one outage into a total one."),

    // JUNIOR
    mcq("JUNIOR", "Your endpoint accepts a page size from the client and passes it straight to the query. What is missing?",
      ["Type coercion", "An upper bound, so a caller cannot request a million rows in one page", "A default sort", "An index"], 1,
      "Unbounded page size is a denial-of-service vector that looks like a legitimate request."),
    mcq("JUNIOR", "What does `Promise.allSettled` give you over `Promise.all`?",
      ["Faster resolution", "Every result, including failures, instead of rejecting on the first error", "Automatic retries", "Sequential execution"], 1,
      "`Promise.all` rejects immediately and abandons the other results, which is rarely what a batch wants."),
    mcq("JUNIOR", "Why is a synchronous `crypto.pbkdf2Sync` in a request handler a problem?",
      ["It is insecure", "It blocks the event loop for its whole duration, stalling every other request", "It cannot be awaited", "It uses too much memory"], 1,
      "The async variant runs on the thread pool. Deliberately slow work must not run on the main thread."),
    mcq("JUNIOR", "What does setting `trust proxy` affect?",
      ["TLS termination", "Whether the app believes X-Forwarded-For and X-Forwarded-Proto headers when behind a load balancer", "Connection pooling", "Compression"], 1,
      "Get it wrong and you either log the proxy's IP for everyone or trust a header a client can forge."),
    mcq("JUNIOR", "A cron-triggered endpoint is publicly reachable. What should protect it?",
      ["Obscurity of the URL", "A shared secret or signed request, checked before doing any work", "Rate limiting alone", "A CAPTCHA"], 1,
      "An unguessable URL is a credential that appears in logs, referrers and proxies."),
    mcq("JUNIOR", "What is the practical consequence of not setting a request timeout on an outbound call?",
      ["Higher memory use only", "A hung dependency holds your handler open indefinitely, exhausting your own capacity", "The call retries forever", "DNS caching fails"], 1,
      "Every outbound call needs a timeout shorter than your own request budget."),
    mcq("JUNIOR", "Why does returning a stack trace in an API error response matter?",
      ["It is large", "It reveals file paths, framework versions and internal structure to an attacker", "It breaks JSON parsing", "Clients cannot read it"], 1,
      "Log the detail with an id and return the id. The user can quote it; an attacker learns nothing."),
    mcq("JUNIOR", "What does connection pooling not solve?",
      ["Connection setup cost", "A slow query holding a connection for seconds", "Limiting concurrency to the database", "Reusing authenticated sessions"], 1,
      "The pool bounds concurrency; it cannot make a slow query fast. A pool full of slow queries is still exhausted."),
    mcq("JUNIOR", "Which is the correct place to enforce a business rule such as 'an order must have at least one item'?",
      ["Only in the frontend", "In the server-side domain logic, with a database constraint where it can be expressed", "In a database trigger only", "In the API gateway"], 1,
      "The frontend is a convenience. The server is the boundary that cannot be bypassed."),
    mcq("JUNIOR", "What does an idempotency key let a client do safely?",
      ["Send requests faster", "Retry a request after a timeout without risking a duplicate side effect", "Skip authentication", "Batch requests"], 1,
      "The client cannot tell a lost response from a lost request. The key lets the server tell."),
    mcq("JUNIOR", "Why prefer cursor pagination over offset for an activity feed?",
      ["Cursors are shorter", "New rows arriving shift offsets, so pages skip or repeat items", "Offset is not supported", "Cursors allow sorting"], 1,
      "Offset also degrades on deep pages because the database must count past every skipped row."),
    mcq("JUNIOR", "What is the risk of logging the full request body on error?",
      ["Log volume only", "Passwords, tokens and personal data end up in logs that are widely readable and long-lived", "Slower error handling", "Encoding problems"], 1,
      "Logs are usually the least-protected copy of your most sensitive data."),
    mcq("JUNIOR", "What does a 502 from your load balancer usually indicate?",
      ["The client sent a bad request", "The upstream application did not return a valid response — it crashed, timed out or refused the connection", "The certificate expired", "Rate limiting"], 1,
      "504 is specifically a timeout. 502 covers the broader case of an upstream that failed to answer properly."),

    // MID
    mcq("MID", "Why is a shared mutable module-level cache dangerous in a clustered Node deployment?",
      ["It uses too much memory", "Each worker has its own copy, so reads are inconsistent depending on which worker answered", "Modules cannot hold state", "It prevents garbage collection"], 1,
      "Either accept per-worker staleness deliberately or move the cache out of process."),
    mcq("MID", "What does backpressure mean when consuming a stream?",
      ["Retrying failed chunks", "Slowing the producer when the consumer cannot keep up, rather than buffering without bound", "Compressing the stream", "Reordering chunks"], 1,
      "Ignoring it turns a slow consumer into unbounded memory growth."),
    mcq("MID", "Which is the strongest reason to separate read and write models?",
      ["Smaller codebase", "Their access patterns and consistency needs genuinely differ, and coupling them constrains both", "It is required for microservices", "It removes the need for transactions"], 1,
      "The cost is duplicated logic and eventual consistency, so it needs a real driver."),
    mcq("MID", "What does a bulkhead pattern isolate?",
      ["Database schemas", "Resources such as thread or connection pools, so one failing dependency cannot consume them all", "Network traffic", "Log streams"], 1,
      "Separate pools per dependency mean a hung third party cannot starve your core path."),
    mcq("MID", "Your service must call a partner API that is occasionally slow. Which combination is soundest?",
      ["Retry until success", "A short timeout, bounded retries with jitter, and a circuit breaker", "A long timeout with no retry", "Queue every call"], 1,
      "Each piece addresses a different failure: timeouts bound the wait, jitter prevents synchronised retries, the breaker stops hammering a dying service."),
    mcq("MID", "What is the risk of running database migrations automatically on application start?",
      ["Slower startup", "Several instances starting at once can run the same migration concurrently", "Migrations cannot be rolled back", "It requires elevated privileges"], 1,
      "Advisory locking makes it safe. Without one, a rolling deploy races itself."),
    mcq("MID", "Why is `SELECT ... FOR UPDATE SKIP LOCKED` useful for a job queue?",
      ["It is faster", "Several workers can claim different rows concurrently without blocking each other", "It prevents duplicates", "It avoids transactions"], 1,
      "Without SKIP LOCKED, workers queue behind the same row and the queue serialises."),
    mcq("MID", "What does OpenTelemetry give you that structured logging does not?",
      ["Lower cost", "Causal links between operations across services, so one request can be followed end to end", "Better formatting", "Automatic alerting"], 1,
      "Logs tell you what happened in one place. Traces tell you what happened in sequence across many."),
    mcq("MID", "Which is the most reliable way to prevent a slow endpoint from taking down the whole service?",
      ["Raise the memory limit", "Bound its concurrency and give it its own timeout, so it cannot consume the shared pool", "Cache its response", "Move it to a separate route"], 1,
      "Isolation is what stops one endpoint's problem becoming everyone's problem."),
    mcq("MID", "What is the danger of using the database as a message queue without care?",
      ["It cannot store messages", "Polling load, lock contention, and rows that stay claimed forever when a worker dies", "Messages cannot be ordered", "It requires a separate schema"], 1,
      "It works well at modest scale with visibility timeouts and SKIP LOCKED, and badly without them."),
    mcq("MID", "Why should a service validate its own configuration at startup?",
      ["To speed up boot", "So a missing or malformed setting fails immediately rather than at 3am on a rare code path", "To generate documentation", "To enable hot reload"], 1,
      "Failing fast at boot turns a latent production incident into a failed deploy."),
    mcq("MID", "What does an outbox table solve?",
      ["Message ordering", "The gap between committing a database change and publishing an event about it", "Duplicate consumers", "Schema evolution"], 1,
      "Writing the event in the same transaction means the two can never disagree; a relay publishes it afterwards."),
    mcq("MID", "Why is 'retry on 500' a dangerous default?",
      ["500s are rare", "The operation may have partially succeeded, so retrying can duplicate its side effects", "Retries are slow", "500 means the client is wrong"], 1,
      "Retry safely only where the operation is idempotent or carries an idempotency key."),
  ],
};

export const MCQ_DEPTH_ENGINEERING: BankDomain[] = [
  FULLSTACK_MCQ,
  FRONTEND_MCQ,
  BACKEND_NODE_MCQ,
];
